---
settings:
  name: Active IQ Unified Manager 9.14
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    # Current repo stanza comes first
    - version-number: "9.14"
      url: /active-iq-unified-manager
    # Additional releases newest to oldest
    # Release in GitHub (typical)
    - version-number: "9.13"
      url: /active-iq-unified-manager-913
    - version-number: "9.12"
      url: /active-iq-unified-manager-912  
    - version-number: "9.11"
      url: /active-iq-unified-manager-911
    - version-number: "9.10"
      url: /active-iq-unified-manager-910
      
sidebar:
  entries:
    - title: Active IQ Unified Manager 9.14 docs
      url: "/index.html"
    - title: Release notes
      url: /reference_release_notes.html
    - title: Get started
      entries:
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html
    - section: install-vapp
    - section: install-linux
    - section: install-windows
    - section: config
    - section: storage-mgmt
    - section: events
    - section: performance-checker
    - section: health-checker
    - section: data-protection
    - section: reporting
    - section: api-automation
    - title: Legal notices
      url: /legal-notices.html
