---
permalink: api-automation/concept_events_api.html
sidebar: sidebar
keywords: view, events, system, details
summary: "The events API enables you to retrieve the events that are generated for the monitored clusters in your data center."
---
= Managing events and alerts
:icons: font
:imagesdir: ../media/

[.lead]
The `events`, `alerts`, and `scripts` APIs under the `management-server` category enable you to manage the events and alerts in your Active IQ Unified Manager environment.

== Viewing and modifying events
Unified Manager receives the events that are generated on ONTAP for the clusters monitored and managed by Unified Manager. By using these APIs, you can view the events generated for your clusters, and resolve and update them.

By running the `GET` method for the `/management-server/events` API, you can query the events in you data center, including historical data. Use the inbuilt filters, such as name, impact level, impact area, severity, state, resource name and resource type, to view specific events. The resource type and area parameters return information about the storage object on which the event has occurred, and the impact area returns the information about the issue for which the event is raised, such as availability, capacity, configuration, security, protection, and performance.

By running the PATCH operation for this API, you can enable the resolution workflow for the event. You can assign and unassigned event to yourself or another user and acknowledge the receipt of the event. On performing the steps on the resources to resolve the issue that triggered the event, you can use this API to mark the event as resolved.


[cols="4*",options="header"]
|===
| Category| HTTP verb| Path| Description
a|
management-server
a|
GET
a|
`/management-server/events`

a|
The response body consists of the event details of the queried events in that data center.
a|
management-server
a|
GET
a|
`/management-server/events/{key}`
a|
Run this API if you want to query a particular event. You can also use the event key to query the details of a specific event and run the next set of operations on the resources. The response body consists of the details of that event.
a|
management-server
a|
PATCH
a|
`management-server/events/{key}``
a|
Run this API to assign an event or change the state to acknowledged or resolved. It is a synchronous operation.
|===

== Managing alerts

Events are automatically and continuously generated. Unified Manager generates an alert only when an event meets certain filter criteria. You can select the events for which alerts should be generated. By using the `/management-server/alerts` API, you can configure alerts to send notifications automatically when specific events or events of certain severity types occur. By using the `/management-server/scripts` API, you can also associate an alert with a script that is executed when an alert is triggered.

[cols="4*",options="header"]
|===
| Category| HTTP verb| Path| Description
a|
management-server
a|
GET
a|
`/management-server/alerts`
``/management-server/alerts/{key}``
a|
Query all the existing alerts in your environment or a specific alert, by sing the alert key. Information, such as 
a|
management-server
a|
GET
a|
`/management-server/events/{key}`
a|
Run this API if you want to query a particular event. You can also use the event key to query the details of a specific event and run the next set of operations on the resources. The response body consists of the details of that event.
a|
management-server
a|
PATCH
a|
`management-server/events/{key}``
a|
Run this API to assign an event or change the state to acknowledged or resolved. It is a synchronous operation.
|===
