---
permalink: api-automation/concept_events_api.html
sidebar: sidebar
keywords: view, events, system, details
summary: "The events and system APIs under the management-server category enable you to retrieve the events that are generated for the monitored clusters in your data center and view the instance details in your Active IQ Unified Manager environment respectively."
---
= Viewing events and system details
:icons: font
:imagesdir: ../media/

[.lead]
The events and system APIs under the management-server category enable you to retrieve the events that are generated for the monitored clusters in your data center and view the instance details in your Active IQ Unified Manager environment respectively.

== Viewing events

By using the `/management-server/events` API, you can query the events in you data center, including historical data. Use the inbuilt filters, such as name, impact level, impact area, severity, state, resource name and resource type, to view specific events. The resource type and area parameters return information about the storage object on which the event has occurred, and the impact area returns the information about the issue for which the event is raised, such as availability, capacity, configuration, security, protection and performance.

You can also use the event key to query the details of a specific event and run the next set of operations on the resources.
[cols="4*",options="header"]
|===
| Category| HTTP verb| Path| Description
a|
management-server
a|
GET
a|
`/management-server/events`

a|
The response body consists of the event details of the queried events in that data center.
a|
management-server
a|
GET
a|
`/management-server/events/\{key}`

a|
Run this API if you want to query a particular event. Enter the event key of the job to view the details. The response body consists of the details of that event.
|===

== Viewing system details

By using the `/management-server/system` API, you can query the instance-specific details of your Unified Manager environment. The API returns information about the product and services, such as the version of Unified Manager installed on your system, UUID, vendor name, host OS, and the name, description, and status of the services running on the Unified Manager instance.
[cols="4*",options="header"]
|===
| Category| HTTP verb| Path| Description
a|
management-server
a|
GET
a|
`/management-server/system`

a|
No input parameter is required for running this API. The system details of the current Unified Manager instance are returned by default.
|===
