---
permalink: api-automation/concept_getting_strated_with_getting_started_with_um_apis.html
sidebar: sidebar
keywords: 
summary: 'Active IQ Unified Manager provides a set of APIs to manage your storage resources on the supported storage systems through a RESTful web service interface for any third-party integration.'
---
= Getting started with Active IQ Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
Active IQ Unified Manager provides a set of APIs to manage your storage resources on the supported storage systems through a RESTful web service interface for any third-party integration.

The _Unified Manager API Developer's Guide_ provides you with information about APIs and sample codes. The information provided in the guide enables you to create RESTful clients of NetApp Manageability software solutions for managing NetApp systems. The APIs are based on the Representational State Transfer (REST) architectural style.

Unified Manager provides API offerings for storage management in your NetApp environment. All the four REST operations Create, Read, Update, and Delete (also known as CRUD) are supported.

*Related information*

xref:concept_api_url_and_categories.adoc[Active IQ Unified Manager API access and categories]

xref:concept_rest_api_access_and_authentication_in_oncommand_api_services.adoc[REST API access and authentication in Active IQ Unified Manager]
