---
permalink: api-automation/concept_job_api.html
sidebar: sidebar
keywords: jobs, view
summary: "You can use the jobs API under the management-server category to view the execution details of asynchronous operations."
---
= Viewing Jobs and system details
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `jobs` API under the `management-server` category to view the execution details of asynchronous operations. The `system` API under the `management-server` category enables you to view the instance details in your Active IQ Unified Manager environment.

== Viewing Jobs

In Active IQ Unified Manager, operations, such as adding and modifying resources are performed by synchronous and asynchronous API invocations. Invocations that are scheduled for asynchronous execution can be tracked by a Job object created for that invocation. Each Job object has a unique key for identification. Each Job object returns the Job object URI for you to access and track the progress of the job. You can use this API for retrieving the details of each execution.

By using this API, you can query all the Job objects for you data center, including historical data. Querying all the jobs, by default, returns the details of the last 20 jobs triggered through the web UI and API interface. Use the inbuilt filters to view specific Jobs. You can also use the Job key to query the details of a specific job and run the next set of operations on the resources.
[cols="4*",options="header"]
|===
| Category| HTTP verb| Path| Description
a|
management-server
a|
GET
a|
`/management-server/jobs`

a|
Returns the job details of all the jobs. Without any sort order, the last submitted Job object is returned on top.
a|
management-server
a|
GET
a|
`/management-server/jobs/\{key}`

Enter the job key of the Job object to view the specific details of that job.

a|
Returns the details of the specific Job object.
|===

== Viewing system details

By using the `/management-server/system` API, you can query the instance-specific details of your Unified Manager environment. The API returns information about the product and services, such as the version of Unified Manager installed on your system, UUID, vendor name, host OS, and the name, description, and status of the services running on the Unified Manager instance.
[cols="4*",options="header"]
|===
| Category| HTTP verb| Path| Description
a|
management-server
a|
GET
a|
`/management-server/system`

a|
No input parameter is required for running this API. The system details of the current Unified Manager instance are returned by default.

|===
