---
permalink: api-automation/reference_intended_audience_for_this_guide.html
sidebar: sidebar
keywords: audience, api, rest
summary: "This section is intended for developers creating applications that interface with the Active IQ Unified Manager software through REST APIs."
---
= Audience for this content
:icons: font
:imagesdir: ../media/

[.lead]
The topics here are intended for developers creating applications that interface with the Active IQ Unified Manager software through REST APIs.

Storage administrators and architects, can refer to this information to gain a basic understanding of how the Unified Manager REST APIs can be used to build client applications to manage and monitor NetApp storage systems.

You should use this information if you want to use the storage provider, ONTAP cluster, and management administration APIs for managing your storage.

[NOTE]
====
You must have one of the following roles: Operator, Storage Administrator, or Application Administrator. You must know the IP address or fully qualified domain name of the Unified Manager server on which you want to execute the REST APIs.
====
