---
permalink: api-automation/reference_authentication_errors.html
sidebar: sidebar
keywords: http, status, code, active iq, unified manager
summary: "While running the APIs or troubleshooting issues, you should be aware of the various HTTP status codes and error codes that are used by Active IQ Unified Manager APIs."
---
= HTTP status codes used in Active IQ Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
While running the APIs or troubleshooting issues, you should be aware of the various HTTP status codes and error codes that are used by Active IQ Unified Manager APIs.

The following table lists the error codes related to authentication:
[cols="3*",options="header"]
|===
| HTTP status code| Status code title| Description
a|
200
a|
OK
a|
Returned on successful execution of synchronous API calls.
a|
201
a|
Created
a|
Creation of new resources by synchronous calls, such as configuration of Active Directory.
a|
202
a|
Accepted
a|
Returned on successful execution of asynchronous calls for provisioning functions, such as creating LUNs and files shares.
a|
400
a|
Invalid request
a|
Indicates input validation failure. User has to correct the inputs, for example, valid keys in a request body.
a|
401
a|
Unauthorized request
a|
You are not authorized to view the resource/Unauthorized.
a|
403
a|
Forbidden request
a|
Accessing the resource you were trying to reach is forbidden.
a|
404
a|
Resource not found
a|
The resource you were trying to reach is not found.
a|
405
a|
Method Not Allowed
a|
Method not allowed.
a|
429
a|
Too Many Requests
a|
Returned when the user sends too many requests within a specific time.
a|
500
a|
Internal server error
a|
Internal server error. Failed to get the response from server. This internal server error may or may not be permanent. For example, if you run a `GET` or `GET ALL` operation and receive this error, it is recommended that you repeat this operation for a minimum of five retries. If it is a permanent error, then the status code returned continues to be 500. If the operation succeeds, the status code returned is 200.
|===
