---
permalink: reporting/concept_reporting_access_points.html
sidebar: sidebar
keywords: 
summary: 'You can gather information in Unified Manager about your clusters to create reports from the UI, MySQL database queries, and REST APIs.'
---
= Access points for generating reports
:icons: font
:imagesdir: ../media/

[.lead]
You can gather information in Unified Manager about your clusters to create reports from the UI, MySQL database queries, and REST APIs.

This guide covers Unified Manager reporting and scheduling through the UI.

There are three ways you can access the reporting capabilities provided by Unified Manager:

* Extracting data directly from the inventory pages in the UI.
* Using Open Database Connectivity (ODBC) and ODBC tools to access all the available objects.
* Executing Unified Manager REST APIs to return the information that you want to review.

This guide covers Unified Manager reporting and scheduling through the UI.

*Related information*

xref:generaltask_um_rest_apis_that_can_be_used_for_reporting.adoc[Unified Manager REST APIs that can be used for reporting]

xref:concept_unified_manager_databases_accessible_for_reporting.adoc[Unified Manager databases accessible for custom reporting]
