---
permalink: reporting/concept_customize_reports.html
sidebar: sidebar
keywords: customize, reports
summary: "There are many ways you can customize views so that you can create a report that contains all the information you need to manage your ONTAP clusters."
---
= Customizing reports
:icons: font
:imagesdir: ../media/

[.lead]
There are many ways you can customize views so that you can create a report that contains all the information you need to manage your ONTAP clusters.

Start with a default inventory page or a custom view, then customize it by adding or removing columns, changing the column order, filtering the data, or sorting on a specific column in ascending or descending order.

Starting in Unified Manager 9.8, you can also download the view in Excel to customize it using advanced features. When done, upload the customized Excel file. If you schedule a report using that view, it uses the customized Excel file to create robust reports you can share.

For more information on customizing reports using Excel, see _Sample Microsoft Excel reports_.

[NOTE]
====
You must have the Application Administrator or Storage Administrator role to manage reports.
====
