---
permalink: performance-checker/concept_add_disks_and_perform_aggregate_layout_reconstruction.html
sidebar: sidebar
keywords: add, disks, perform, aggregate, layout, reconstruction
summary: "You can add disks to an aggregate to increase the storage capacity and the performance of that aggregate. After adding the disks, you only see an improvement in performance after reconstructing the aggregate."
---
= Add disks and perform aggregate layout reconstruction
:icons: font
:imagesdir: ../media/

[.lead]
You can add disks to an aggregate to increase the storage capacity and the performance of that aggregate. After adding the disks, you only see an improvement in performance after reconstructing the aggregate.

When you receive a system-defined threshold event on the Event details page, the event description text lists the name of the aggregate that is having the problem. You can add disks and reconstruct data on this aggregate.

The disks you add to the aggregate must already exist in the cluster. If the cluster does not have extra disks available, you might need to contact your administrator or purchase more disks. You can use ONTAP System Manager or the ONTAP commands to add disks to an aggregate.

http://www.netapp.com/us/media/tr-3838.pdf[Technical Report 3838: Storage Subsystem Configuration Guide]
