---
permalink: performance-checker/concept_what_happens_when_a_performance_threshold_policy_is_changed_opm.html
sidebar: sidebar
keywords: 
summary: 'If you adjust the counter value or duration of an existing performance threshold policy, the policy change is applied to all storage objects that use the policy. The new setting takes place immediately, and Unified Manager begins to compare performance counter values to the new threshold settings for all newly collected performance data.'
---
= What happens when a performance threshold policy is changed
:icons: font
:imagesdir: ../media/

[.lead]
If you adjust the counter value or duration of an existing performance threshold policy, the policy change is applied to all storage objects that use the policy. The new setting takes place immediately, and Unified Manager begins to compare performance counter values to the new threshold settings for all newly collected performance data.

If any active events exist for objects that are using the changed threshold policy, the events are marked as obsolete, and the threshold policy begins monitoring the counter as a newly defined threshold policy.

When viewing the counter on which the threshold has been applied in the Counter Charts Detailed View, the critical and warning threshold lines reflect the current threshold settings. The original threshold settings do not appear on this page even if you view historical data when the old threshold setting was in effect.

[NOTE]
====
Because older threshold settings do not appear in the Counter Charts Detailed View, you might see historical events that appear below the current threshold lines.
====
