---
permalink: performance-checker/concept_using_a_threshold_policy_with_the_node_failover_planning_page.html
sidebar: sidebar
keywords: 
summary: 'You can create a node threshold policy so that you can be notified in the Performance/Node Failover Planning page when a potential failover would degrade the performance of the takeover node to an unacceptable level.'
---
= Using a threshold policy with the Node Failover Planning page
:icons: font
:imagesdir: ../media/

[.lead]
You can create a node threshold policy so that you can be notified in the Performance/Node Failover Planning page when a potential failover would degrade the performance of the takeover node to an unacceptable level.

The system-defined performance threshold policy named "`Node HA pair over-utilized`" generates a warning event if the threshold is breached for six consecutive collection periods (30 minutes). The threshold is considered breached if the combined performance capacity used of the nodes in an HA pair exceeds 200%.

The event from the system-defined threshold policy alerts you to the fact that a failover will cause the latency of the takeover node to increase to an unacceptable level. When you see an event that is generated by this policy for a particular node, you can navigate to the Performance/Node Failover Planning page for that node to view the predicted latency value due to a failover.

In addition to using this system-defined threshold policy, you can create threshold policies by using the "`Performance Capacity Used - Takeover`" counter, and then apply the policy to selected nodes. Specifying a threshold lower than 200% enables you to receive an event before the threshold for the system-defined policy is breached. You can also specify the minimum period of time for which the threshold is exceeded to less than 30 minutes if you want to be notified before the system-defined policy event is generated.

For example, you can define a threshold policy to generate a warning event if the combined performance capacity used of the nodes in an HA pair exceeds 175% for more than 10 minutes. You can apply this policy to Node1 and Node2, which form an HA pair. After receiving a warning event notification for either Node1 or Node2, you can view the Performance/Node Failover Planning page for that node to assess the estimated performance impact on the takeover node. You can take corrective actions to avoid overloading the takeover node if a failover does happen. If you take action when the combined performance capacity used of the nodes is under 200%, the takeover node's latency does not reach an unacceptable level even if a failover happens during this time.

*Related information*

xref:concept_how_user_defined_performance_threshold_policies_work_opm.adoc[How user-defined performance threshold policies work]

xref:concept_what_happens_when_a_performance_threshold_policy_is_breached_opm.adoc[What happens when a performance threshold policy is breached]

xref:task_creating_user_defined_performance_threshold_policies.adoc[Creating user-defined performance threshold policies]
