---
permalink: performance-checker/reference_understanding_and_using_the_node_failover_planning_page.html
sidebar: sidebar
keywords: 
summary: 'The Performance/Node Failover Planning page estimates the performance impact on a node if the node’s high-availability \(HA\) partner node fails. Unified Manager bases the estimates on the historical performance of the nodes in the HA pair.'
---
= Understanding and using the Node Failover Planning page
:icons: font
:imagesdir: ../media/

[.lead]
The Performance/Node Failover Planning page estimates the performance impact on a node if the node's high-availability (HA) partner node fails. Unified Manager bases the estimates on the historical performance of the nodes in the HA pair.

Estimating the performance impact of a failover helps you to plan in the following scenarios:

* If a failover consistently degrades the takeover node's estimated performance to an unacceptable level, you can consider taking corrective actions to reduce the performance impact due to a failover.
* Before initiating a manual failover to perform hardware maintenance tasks, you can estimate how the failover affects the performance of the takeover node in order to determine the best time to perform the task.

*Related information*

xref:concept_using_the_failover_planning_page_to_determine_corrective_actions.adoc[Using the Node Failover Planning page to determine corrective actions]

xref:reference_components_of_the_node_failover_planning_page.adoc[Components of the Node Failover Planning page]

xref:concept_using_a_threshold_policy_with_the_node_failover_planning_page.adoc[Using a threshold policy with the Node Failover Planning page]

xref:task_using_the_perf_capacity_used_breakdown_chart_for_failover_planning.adoc[Using the Performance Capacity Used Breakdown chart for failover planning]
