---
permalink: performance-checker/task_identify_bully_workloads_involved_in_performance_event.html
sidebar: sidebar
keywords: identify, bully workloads, dynamic, performance, event
summary: "In Unified Manager, you can identify which workloads have the highest deviation in usage for a cluster component in contention. Identifying these workloads helps you understand why certain volumes on the cluster have slow response times (latency)."
---
= Identifying bully workloads involved in a dynamic performance event
:icons: font
:imagesdir: ../media/

[.lead]
In Unified Manager, you can identify which workloads have the highest deviation in usage for a cluster component in contention. Identifying these workloads helps you understand why certain volumes on the cluster have slow response times (latency).

*What you'll need*

* You must have the Operator, Application Administrator, or Storage Administrator role.
* There must be new, acknowledged, or obsolete dynamic performance events.

The Event details page displays a list of the user-defined and system-defined workloads ranked by the highest usage of the component or most impacted by the event. The values are based on the peaks that Unified Manager identified when it detected and last analyzed the event.

.Steps
. Display the Event details page to view information about the event.
. In the Workload Latency and Workload Activity charts, select *Bully Workloads*.
. Hover your cursor over the charts to view the top user-defined bully workloads that are affecting the component.
