---
permalink: performance-checker/task_move_workloads_to_node_in_different_ha_pair.html
sidebar: sidebar
keywords: move, workloads, node, different, ha pair
summary: "You can use Unified Manager to help identify an aggregate on a node in a different high-availability (HA) pair that has more free performance capacity than the HA pair where your workloads are currently running. Then you can move selected volumes to aggregates on the new HA pair."
---
= Moving workloads to a node in a different HA pair
:icons: font
:imagesdir: ../media/

[.lead]
You can use Unified Manager to help identify an aggregate on a node in a different high-availability (HA) pair that has more free performance capacity than the HA pair where your workloads are currently running. Then you can move selected volumes to aggregates on the new HA pair.

*What you'll need*

* You must have the Operator, Application Administrator, or Storage Administrator role.
* Your cluster must consist of a minimum of two HA pairs
+
You cannot use this remediation process if you have only one HA pair in your cluster.

* You must have recorded the names of the two nodes in the HA pair that are currently having a performance issue.
* You must have recorded the date and time at which the nodes received the performance event.
* Unified Manager must have collected and analyzed performance data for a month or longer.

Moving high-performing workloads to an aggregate on a node with more free performance capacity allows workloads on both nodes to perform more efficiently. This procedure helps you to identify the following resources so that you can move high-performing workloads to a node that has more free performance capacity on a different HA pair:

* The nodes in a different HA pair on the same cluster that have the greatest free performance capacity
* The aggregates on the new nodes that have the greatest free performance capacity
* The highest-performing volumes on the current nodes

.Steps
. Identify the nodes that are part of a different HA pair on the same cluster:
 .. On the *Event Details* page, click the name of the cluster on which the nodes reside.
+
The cluster details are displayed in the Performance/Cluster Landing page.

 .. On the *Summary* page, click *Nodes* from the *Managed Objects* pane.
+
The list of nodes on this cluster is displayed in the Performance: All Nodes view.

 .. Write down the names of the nodes that are in different HA pairs from the HA pair that is currently having a performance issue.
. Identify a node in the new HA pair that has the greatest free performance capacity:
 .. On the *Performance: All Nodes* view, click the *Performance Capacity Used* column to sort the nodes by least percentage used.
+
This provides a list of potential nodes to which you might want to move workloads.

 .. Write down the name of the node on a different HA pair to which you want to move the workloads.
. Identify an aggregate on the new node that has the greatest free performance capacity:
 .. On the *Performance: All Nodes* view, click the node.
+
The node details are displayed in the Performance/Node Explorer page.

 .. In the *View and Compare* menu, select *Aggregates on this Node*.
+
The aggregates on this node are displayed in the grid.

 .. Click the *Performance Capacity Used* column to sort the aggregates by least used.
+
This provides a list of potential aggregates to which you might want to move workloads.

 .. Write down the name of the aggregate to which you want to move the workloads.
. Identify the high-performing workloads from the nodes that received the event:
 .. Return to the *Event* details page for the event.
 .. In the *Affected Volumes* field, click the link for the number of volumes for the first node.
+
The Performance: All Volumes view is displayed with a filtered list of the volumes on that node.

 .. Click the *Total Capacity* column to sort the volumes by the largest allocated space.
+
This provides a list of potential volumes that you might want to move.

 .. Write down the names of the volumes that you want to move, and the names of the current aggregates on which they reside.
 .. Perform steps 4c and 4d for the second node that was part of this event to identify possible volumes that you want to move from that node as well.
. Move the volumes to the aggregates that you identified as having greatest free performance capacity on the new node.
+
You can perform the move operation by using ONTAP System Manager, OnCommand Workflow Automation, ONTAP commands, or a combination of these tools.

After a few days, you can check whether you are receiving the same type of events from this node or aggregate.
