---
permalink: performance-checker/task_identifying_victim_workloads_involved_in_a_performance_event.html
sidebar: sidebar
keywords: 
summary: 'In Unified Manager, you can identify which volume workloads have the highest deviation in response time \(latency\) caused by a storage component in contention. Identifying these workloads helps you understand why the client applications accessing them have been performing slower than usual.'
---
= Identifying victim workloads involved in a dynamic performance event
:icons: font
:imagesdir: ../media/

[.lead]
In Unified Manager, you can identify which volume workloads have the highest deviation in response time (latency) caused by a storage component in contention. Identifying these workloads helps you understand why the client applications accessing them have been performing slower than usual.

* You must have the Operator, Application Administrator, or Storage Administrator role.
* There must be new, acknowledged, or obsolete dynamic performance events.

The Event details page displays a list of the user-defined and system-defined workloads, ranked by the highest deviation in activity or usage on the component or most impacted by the event. The values are based on the peaks that Unified Manager identified when it detected and last analyzed the event.

. Display the Event details page to view information about the event.
. In the Workload Latency and Workload Activity charts, select *Victim Workloads*.
. Hover your cursor over the charts to view the top user-defined workloads that are affecting the component, and the name of the victim workload.

*Related information*

xref:concept_how_unified_manager_determines_the_performance_impact_for_an_incident.adoc[How Unified Manager determines the performance impact for an event]

xref:concept_cluster_components_and_why_they_can_be_in_contention.adoc[Cluster components and why they can be in contention]

xref:reference_performance_event_analysis_and_notification.adoc[Performance event analysis and notification]

xref:task_displaying_information_about_a_performance_event.adoc[Displaying information about performance events]

xref:task_identifying_bully_workloads_involved_in_a_performance_event.adoc[Identifying bully workloads involved in a dynamic performance event]

xref:task_identifying_shark_workloads_involved_in_a_performance_event.adoc[Identifying shark workloads involved in a dynamic performance event]
