---
permalink: performance-checker/task_move_workloads_to_another_node_in_different_ha_pair.html
sidebar: sidebar
keywords: move, workloads, another, node, different, ha pair
summary: "You can use Unified Manager to help identify an aggregate on a node in a different HA pair that is less busy than the HA pair where your workloads are currently running. Then you can move selected volumes to aggregates on the new HA pair. Moving high-performing workloads to an aggregate on a less busy node allows workloads on both nodes to perform more efficiently."
---
= Moving workloads to another node in a different HA pair
:icons: font
:imagesdir: ../media/

[.lead]
You can use Unified Manager to help identify an aggregate on a node in a different HA pair that is less busy than the HA pair where your workloads are currently running. Then you can move selected volumes to aggregates on the new HA pair. Moving high-performing workloads to an aggregate on a less busy node allows workloads on both nodes to perform more efficiently.

*What you'll need*

* You must have the Operator, Application Administrator, or Storage Administrator role.
* Your cluster must consist of a minimum of two HA pairs; you cannot use this remediation process if you have only one HA pair in your cluster.
* You must have recorded the names of the two nodes in the HA pair that are currently having the performance issue.
* You must have recorded the date and time at which the nodes received the performance event.
* Unified Manager must have collected and analyzed a month or more of performance data.

These steps help you identify the following resources so that you can move high-performing workloads to a lower utilized node on a different HA pair:

* The nodes in a different HA pair on the same cluster that are less utilized
* The aggregates on the new nodes that are the least utilized
* The highest-performing volumes on the current nodes

.Steps
. Identify the nodes that are part of a different HA pair on the same cluster:
 .. In the left navigation pane, click *Storage* > *Clusters* and select *Performance* > *All Clusters* from the View menu.
+
The Performance: All Clusters view is displayed.

 .. Click the number in the *Node Count* field for the current cluster.
+
The Performance: All Nodes view is displayed.

 .. Write down the names of the nodes that are in different HA pairs from the HA pair that is currently having the performance issue.
. Identify a node in the new HA pair that is the least utilized:
 .. Click the *Utilization* column to sort the nodes by least utilized.
+
You can also identify those nodes that have the greatest *Free Capacity*. This provides a list of potential nodes to which you might want to move workloads.

 .. Write down the name of the node to which you want to move the workloads.
. Identify an aggregate on the new node that is the least utilized:
 .. In the left navigation pane, click *Storage* > *Aggregates* and select *Performance* > *All Aggregates* from the View menu.
+
The Performance: All Aggregates view is displayed.

 .. Click *Filtering*, select *Node* from the left drop-down menu, type the name of the node in the text field, and then click *Apply Filter*.
+
The Performance: All Aggregates view is redisplayed with the list of aggregates that are available on this node.

 .. Click the *Utilization* column to sort the aggregates by least utilized.
+
You can also identify those aggregates that have the greatest *Free Capacity*. This provides a list of potential aggregates to which you might want to move workloads.

 .. Write down the name of the aggregate to which you want to move the workloads.
. Identify the high-performing workloads from the nodes that received the event:
 .. Return to the *Event* details page for the event.
 .. In the *Affected Volumes* field, click the link for the number of volumes for the first node.
+
The Performance: All Volumes view is displayed with a filtered list of the volumes on that node.

 .. Click the *Total Capacity* column to sort the volumes by the largest allocated space.
+
This provides a list of potential volumes that you might want to move.

 .. Write down the names of the volumes that you want to move, and the names of the current aggregates on which they reside.
 .. Perform steps 4c and 4d for the second node that was part of this event to identify possible volumes that you want to move from that node as well.
. Move the volumes to the aggregates you identified as having low utilization on the new node.
+
You can perform the move operation by using ONTAP System Manager, OnCommand Workflow Automation, ONTAP commands, or a combination of these tools.

After a few days, check to see whether you are receiving the same type of events from this node or aggregate.
