---
permalink: storage-mgmt/concept_manage_performance_service_levels.html
sidebar: sidebar
keywords: manage, performance service level, PSL, User-defined, system-defined PSL, bursty, Database PSL, extreme PSL, beyond extreme PSL
summary: "Performance service level calculations and management."
---
= Performance Service Levels
:icons: font
:imagesdir: ../media/

[.lead]
A Performance Service Level (PSL) enables you to define the performance and storage objectives for a workload. You can assign a PSL to a workload when initially creating the workload, or afterwards by editing the workload.

The management and monitoring of storage resources are based on Service Level Objectives (SLOs). SLOs are defined by service level agreements that are based on required performance and capacity. In Unified Manager, SLOs refer to the PSL definitions of the applications that are running on NetApp storage. Storage services are differentiated based on the performance and utilization of the underlying resources. A PSL is a description of the storage service objectives. A PSL enables the storage provider to specify the performance and capacity objectives for the workload.  When you assign a PSL on a workload, the corresponding workload on ONTAP is managed by its performance and capacity objectives. Each PSL is governed by peak, expected, and absolute minimum IOPs, and expected latency.

Unified Manager has the following types of PSLs:

* *System-defined*: Unified Manager provides a few canned policies that cannot be changed. These predefined PSLs are:

** Extreme Performance
** Performance
** Value
+
The Extreme Performance, Performance, and Value PSLs are applicable for most of the common storage workloads in a data center.
+
Unified Manager also offers three Performance Service Levels for database applications. These are extremely high-performance PSLs that support bursty IOPS and are appropriate for database applications with the highest throughput demand.

** Extreme for Database Logs
** Extreme for Database Shared Data
** Extreme for Database Data

* *User-defined*: If the predefined Performance Service Levels do not meet your requirements, then you can create new PSLs to meet your needs. For information, see link:../storage-mgmt/task_create_and_edit_psls.html[Creating and editing Performance Service Levels].
* *Beyond Extreme*: The Beyond Extreme PSLs are the system-recommended PSLs that are suggested for workloads that demand IOPs higher than Extreme. The workloads are internally analyzed based on their IOPS, capacity, and latency, and a Beyond Extreme PSL is recommended for each of these workloads on the *Storage > Workloads > All Workloads* screen. You can apply the PSLs to the workloads to ensure an optimum performance.
+
The IOPs parameters for the workloads are dynamically generated, depending on the workload behavior, and appended to the name of the Beyond Extreme PSL in the format `Beyond Extreme <number-(peak IOPS/TB)> <number(expected IOPS/TB)>`. For example, if the system determines a workload to have the peak and expected IOPs as `106345` and `37929` respectively, the Beyond Extreme PSL that is generated for the workload is named as `Beyond Extreme 106345 37929`. Though these PSLs are recommended by the system, when you assign them to workloads, these PSLs are labeled as `User-defined` in type.

== Managing workloads by assigning PSLs
You can access PSLs from the *Policies* > *Performance Service Levels* page and by using the storage provider APIs. Managing storage workloads by assigning PSLs to them is convenient as you do not have to individually manage the storage workloads. Any modifications can also be managed by reassigning another PSL rather than managing them individually. Unified Manager helps you to assign PSLs on your workloads based on internal assessment and recommendations.

For information on assigning system-recommended PSLs to workloads, see link:..//storage-mgmt/concept_assign_policies_on_workloads.html#assigning-system-recommended-psls-to-workloads[Assigning system-recommended PSLs to workloads]

The Performance Service Levels page lists the available PSL policies and enables you to add, edit, and delete them.

[NOTE]
You cannot modify a PSL that is system-defined or that is currently assigned to a workload. You cannot delete a PSL that is assigned to a workload, or if it is the only available PSL.

This page displays the following information:
[options="header"]
|===

| Field| Description
a|
Name
a|
Name of the PSL.

a|
Type
a|
Whether the policy is system-defined or user-defined.

a|
Expected IOPS/TB
a|
Minimum number of IOPS that an application is expected to perform on a LUN or file share. Expected IOPS specifies the minimum expected IOPS allocated, based on the storage object allocated size.

a|
Peak IOPS/TB
a|
Maximum number of IOPS that an application can perform on a LUN or file share. Peak IOPS specifies the maximum possible IOPS allocated, based on the storage object allocated size or the storage object used size.

Peak IOPS are based on an allocation policy. The allocation policy is either allocated-space or used-space. When the allocation policy is set to allocated-space, the peak IOPS is calculated based on the size of the storage object. When the allocation policy is set to used-space, the peak IOPS is calculated based on the amount of data stored in the storage object, taking into account storage efficiencies. By default, the allocation policy is set to used-space.

a|
Absolute minimum IOPS
a|
The absolute minimum IOPS is used as an override, when the expected IOPS is less than this value. The default values of the system-defined PSLs are the following:

* Extreme Performance: If expected IOPS >= 6144/TB, then absolute minimum IOPS = 1000
* Performance: If expected IOPS >= 2048/TB and < 6144/TB, then absolute minimum IOPS = 500
* Value: If expected IOPS >= 128/TB and < 2048/TB, then absolute minimum IOPS = 75

The default values of the system-defined database PSLs are the following:

* Extreme for Database Logs: If expected IOPS >= 22528, then absolute minimum IOPS = 4000
* Extreme for Database Shared Data: If expected IOPS >= 16384, then absolute minimum IOPS = 2000
* Extreme for Database Data: If expected IOPS >= 12288, then absolute minimum IOPS = 2000

The higher value of the absolute minimum IOPS for custom PSLs can be a maximum of 75000. The lower value is calculated as the following:

1000/expected latency

a|
Expected latency
a|
Expected latency for storage IOPS in milliseconds per operation (ms/op).
a|
Capacity
a|
Total available and used capacity in the clusters.
a|
Workloads
a|
Number of storage workloads that have been assigned the PSL.
|===
For information about how the peak IOPS and expected IOPs help in achieving consistent differentiated performance on ONTAP clusters, see the following KB article:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F[What is Performance Budgeting?]

=== Events generated for workloads breaching the threshold defined by PSLs

Note that if workloads exceed the expected latency value for 30% of the time during the previous hour, Unified Manager generates one of the following events to notify you of a potential performance issue:

* Workload Volume Latency Threshold Breached as defined by Performance Service Level Policy
* Workload LUN Latency Threshold Breached as defined by Performance Service Level Policy.

You may want to analyze the workload to see what may be causing the higher latency values.

For more information, see the following links:

* link:../events/reference_volume_events.html#impact-area-performance[Volume events]
* link:../performance-checker/concept_what_happens_when_performance_threshold_policy_is_breached.html[What happens when a performance threshold policy is breached]
* link:..//performance-checker/concept_how_unified_manager_uses_workload_response_time.html[How Unified Manager uses workload latency to identify performance issues]
* link:../performance-checker/concept_what_performance_events_are.html[What performance events are]

=== System-defined PSLs

The following table provides information about the system-defined PSLs:
[options="header"]
|===
| Performance Service Level| Description and use case| Expected latency (ms/op)| Peak IOPS| Expected IOPS| Absolute minimum IOPS
a|
Extreme Performance
a|
Provides extremely high throughput at a very low latency

Ideal for latency-sensitive applications

a|
1
a|
12288
a|
6144
a|
1000
a|
Performance
a|
Provides high throughput at a low latency

Ideal for database and virtualized applications

a|
2
a|
4096
a|
2048
a|
500
a|
Value
a|
Provides high storage capacity and moderate latency

Ideal for high-capacity applications such as email, web content, file shares, and backup targets

a|
17
a|
512
a|
128
a|
75
a|
Extreme for Database Logs
a|
Provides maximum throughput at the lowest latency.

Ideal for database applications supporting database logs. This PSL provides the highest throughput because database logs are extremely bursty and logging is constantly in demand.

a|
1
a|
45056
a|
22528
a|
4000
a|
Extreme for Database Shared Data
a|
Provides very high throughput at the lowest latency.

Ideal for database applications data that is stored in a common data store, but is shared across databases.

a|
1
a|
32768
a|
16384
a|
2000
a|
Extreme for Database Data
a|
Provides high throughput at the lowest latency.

Ideal for database applications data, such as database table information and metadata.

a|
1
a|
24576
a|
12288
a|
2000
|===
