---
permalink: storage-mgmt/concept_use_unified_manager_rest_apis_ocum.html
sidebar: sidebar
keywords: use, unified manager, rest, apis
summary: "Active IQ Unified Manager provides you with REST APIs to view the information about monitoring and managing your storage environment. APIs also allow provisioning and managing storage objects based on policies."
---
= Use Unified Manager REST APIs
:icons: font
:imagesdir: ../media/

[.lead]
Active IQ Unified Manager provides you with REST APIs to view the information about monitoring and managing your storage environment. APIs also allow provisioning and managing storage objects based on policies.

You can also execute ONTAP APIs on all ONTAP-managed clusters by using the API gateway supported by Unified Manager.

For information about Unified Manager REST APIs, see link:../api-automation/concept_get_started_with_um_apis.html[Getting started with Active IQ Unified Manager REST APIs].

[NOTE]
====
When adding an ONTAP cluster with version 9.14.1 or later, communication occurs through the cloud agent feature. ONTAP automatically creates an internal service account user with read-only privileges (for example, clus-agent-xxxx). Do not delete this `clus-agent` user from the ONTAP clusters, or Unified Manager will stop collecting data from those clusters.
====

// 2025-6-11, OTHERDOC-133
// 2025-8-20, OTHERDOC-149