---
permalink: storage-mgmt/task_editing_user_and_group_quota_email_addresses.html
sidebar: sidebar
keywords: 
summary: 'You can modify the email addresses based on the user quota associated with clusters, storage virtual machines \(SVMs\), volumes, qtrees, users, or user groups. You can modify the email address when you want to override the email address generated by rules specified in the Rules to Generate User and Group Quota Email Address dialog box.'
---
= Editing user and group quota email addresses
:icons: font
:imagesdir: ../media/

[.lead]
You can modify the email addresses based on the user quota associated with clusters, storage virtual machines (SVMs), volumes, qtrees, users, or user groups. You can modify the email address when you want to override the email address generated by rules specified in the Rules to Generate User and Group Quota Email Address dialog box.

* You must have the Operator, Application Administrator, or Storage Administrator role.
* You must have reviewed the xref:reference_rules_to_generate_user_and_group_quota_email_address_dialog_box.adoc[guidelines for creating rules].

If you edit an email address, the rules to generate the user and group quota email addresses are no longer applicable to the quota. For notifications to be sent to the email address generated by the rules specified, you must delete the email address and save the change.

. In the left navigation pane, click *Storage* > *SVMs*.
. In the Health: All Storage VMs view, select an SVM and then click the User and Group Quotas tab.
. Click *Edit Email Address* below the row of tabs.
. In the Edit Email Address dialog box, perform the appropriate action:
+
|===
| If...| Then...
a|
You want notifications to be sent to the email address generated by the rules specified
a|

 .. Delete the email address in the *Email Address* field.
 .. Click *Save*.
 .. Refresh the browser by pressing F5 to reload the Edit Email Address dialog box.
 The email address generated by the specified rule is displayed in the *Email Address* field.

a|
You want notifications to be sent to a specified email address
a|

 .. Modify the email address in the *Email Address* field.
 .. Click *Save*.
 The rules to generate the user and group quota email addresses are no longer applicable to the quota.

+
|===

*Related information*

xref:task_creating_rules_to_generate_email_addresses.adoc[Creating rules to generate email addresses]
