---
permalink: storage-mgmt/task_create_and_edit_psls.html
sidebar: sidebar
keywords: 
summary: 'When the system-defined Performance Service Levels do not match your workload requirements, you can create your own Performance Service Levels that are optimized for your workloads.'
---
= Creating and editing Performance Service Levels
:icons: font
:imagesdir: ../media/

[.lead]
When the system-defined Performance Service Levels do not match your workload requirements, you can create your own Performance Service Levels that are optimized for your workloads.

* You must have the Application Administrator role.
* The Performance Service Level name must be unique, and you cannot use the following reserved keywords:
+
`Prime`, `Extreme`, `Performance`, `Value`, `Unassigned`, `Learning`, `Idle`, `Default`, and `None`.

You create and edit custom Performance Service Levels from the Performance Service Levels page by defining the service level objectives you require for the applications that will access storage.

[NOTE]
====
You cannot modify a Performance Service Level if it is currently assigned to a workload.
====

. In the left navigation pane under *Settings*, select *Policies* > *Performance Service Levels*.
. In the Performance Service Levels page, click the appropriate button depending on whether you want to create a new Performance Service Level or if you want to edit an existing Performance Service Level.
+
|===
| To...| Follow these steps...
a|
Create a new Performance Service Level
a|
Click *Add*.
a|
Edit an existing Performance Service Level
a|
Select an existing Performance Service Level, and then click *Edit*.
|===
The page to add or edit a Performance Service Level is displayed.

. Customize the Performance Service Level by specifying the performance objectives, and then click *Submit* to save the Performance Service Level.

You can apply the new or changed Performance Service Level to workloads (LUNs, NFS File Shares, CIFS Shares) from the Workloads page or when provisioning a new workload.

*Related information*

xref:concept_manage_performance_service_levels.adoc[Managing Performance Service Levels]

xref:concept_all_workloads.adoc[Viewing workloads]

xref:task_provision_luns.adoc[Provisioning LUNs]

xref:task_provision_fileshares.adoc[Provisioning file share volumes]
