---
permalink: health-checker/concept_manage_cluster_security_objectives.html
sidebar: sidebar
keywords: cluster, security, manage, objectives
summary: "Unified Manager provides a dashboard that identifies how secure your ONTAP clusters, storage virtual machines (SVMs), and volumes are based on recommendations defined in the NetApp Security Hardening Guide for ONTAP 9."
---
= Managing cluster security objectives
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager provides a dashboard that identifies how secure your ONTAP clusters, storage virtual machines (SVMs), and volumes are based on recommendations defined in the _NetApp Security Hardening Guide for ONTAP 9_.

The goal of the security dashboard is to show any areas where your ONTAP clusters do not align with the NetApp recommended guidelines so that you can fix these potential issues. In most cases you will fix the issues using ONTAP System Manager or the ONTAP CLI. Your organization may not follow all of the recommendations, so in some cases you will not need to make any changes.

See the http://www.netapp.com/us/media/tr-4569.pdf[NetApp Security Hardening Guide for ONTAP 9] (TR-4569) for detailed recommendations and resolutions.

In addition to reporting security status, Unified Manager also generates security events for any cluster or SVM that has security violations. You can track these issues in the Event Management inventory page and you can configure alerts for these events so that your storage administrator is notified when new security events occur.

For more information, see link:../health-checker/concept_what_security_criteria_is_being_evaluated.html[What security criteria are being evaluated].
