---
permalink: health-checker/concept_configure_backup_for_windows.html
sidebar: sidebar
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup
summary: "Active IQ Unified Manager supports backup and restore using NetApp Snapshots on Windows operating system with the help of LUN using iSCSI protocol."
---
= Configure backup on Windows in Active IQ Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
Active IQ Unified Manager supports backup and restore using NetApp Snapshots on Windows operating system with the help of LUN using iSCSI protocol.

Snapshot based backup can be taken while all Unified Manager services are running. A consistent state of database is captured as part of the Snapshot as the backup puts a global read lock on the entire database that prevents any concurrent write. For your Unified Manager system installed on Windows OS to perform backup and restore using NetApp Snapshots, you should first configure Unified Manager backup to Snapshot based using the maintenance console.

Before you configure Unified Manager for creating Snapshot copies, you should perform the following configuration tasks.

* Configure ONTAP cluster
* Configure Windows host machine

== Configure a backup location for Active IQ Unified Manager on Windows

You should configure the volume for storing Snapshot copies after backing up Unified Manager on Windows.

.Before you begin

The cluster, storage VM, and volume must meet the following requirements:

* Cluster requirements:
 ** ONTAP 9.3 or greater must be installed
 ** It should be geographically close to the Unified Manager server
 ** It is monitored by Unified Manager
* Storage VM requirements:
 ** iSCSI connectivity on ONTAP cluster
 ** iSCSI protocol must be enabled for the configured machine
 ** You should have a dedicated volume and LUN for backup configuration. The selected volume should contain only one LUN and nothing else.
 ** The size of the LUN should be at least twice the data size expected to be handled in the 9.9 Active IQ Unified Manager.
+
This sets the same size requirement on volume as well.

 ** Make sure All Read/Write access is selected
 ** Make sure that Superuser Access is set to "`any`" in the export policy
* Volume and LUN requirements:
 ** The volume should be at least double the size of the Unified Manager MySQL data directory.
 ** The security style must be set to Windows
 ** The local snapshot policy must be disabled
 ** Volume autosize should be enabled
 ** The performance service level should be set to a policy with high IOPS and low latency, such as "`Extreme`"

== Configure an ONTAP cluster for backup and restore in Active IQ Unified Manager

You need to perform few pre-configuration steps on ONTAP clusters before you can back up and restore Active IQ Unified Manager using Snapshot copy on Windows systems.

You can configure ONTAP cluster using either the command prompt or System Manager user interface. The configuration of ONTAP cluster involves configuring Data LIFs to be available to be assigned as iSCSI LIFs to the storage VM. The next step is to configure an iSCSI enabled storage VM using the System Manager user interface. You will need to configure a static network route for this storage VM to control how LIFs use the network for outbound traffic.

[NOTE]
====
You should have a dedicated volume and a LUN for backup configuration. The selected volume should include only one LUN. The size of the LUN should be at least twice the data size expected to be handled by Active IQ Unified Manager.
====

You need to perform the following configuration:

.Steps
. Configure a iSCSI enabled storage VM or use an existing storage VM that has the same configuration.
. Configure a network route for the configured storage VM.
. Configure a volume of appropriate capacity and a single LUN inside ensuring that the volume is dedicated only for this LUN.
[NOTE]
In a scenario when the LUN is created on System Manager, unmapping the LUN might delete the igroup, and restore might fail. To avoid this scenario, ensure that while creating a LUN, it is created explicitly and is not deleted when the LUN is unmapped.

. Configure an initiator group in the storage VM.
. Configure a port set.
. Integrate the igroup with the portset.
. Map the LUN to the igroup.

== Configure a Windows host machine in Active IQ Unified Manager

You need to configure your Windows host machine before you can use NetApp Snapshot to back up and restore Active IQ Unified Manager.
To start the Microsoft iSCSI initiator on a Windows host machine, type "`iscsi`" in the search bar and click *iSCSI Initiator*.

.Before you begin

You should clean up any previous configurations on the host machine.

If you are trying to start the iSCSI initiator on a fresh installation of Windows, you are prompted for confirmation, and on your confirmation, the iSCSI Properties dialog box is displayed. If it is an existing Windows installation, then the iSCSI Properties dialog box displayed with a target that is either inactive or trying to connect. So, you will need to ensure that all the previous configurations on the Windows host are removed.

.Steps
. Clean up any previous configurations on the host machine.
. Discover the target portal.
. Connect to the target portal.
. Connect using multipath to the target portal.
. Discover both the LIFs.
. Discover the LUN configured in the Windows machine as a device.
. Configure the discovered LUN as a new volume drive in Windows.

== Specify the destination location for Snapshot copies on Windows in Active IQ Unified Manager

You should configure the destination location for Active IQ Unified Manager Snapshot copies on a volume that you have already configured in one of your ONTAP clusters. You should use maintenance console to define the location.

* You must have the administrator privilege for Windows host on which Active IQ Unified Manager is installed.
* You must have a user ID and password authorized to log in to the maintenance console of the Unified Manager server.
* You must have the Cluster Management IP address, the name of the storage VM, the name of the volume, LUN name, and the storage system user name and password.
* You must have mounted the volume as a network drive to the Active IQ Unified Manager host, and you must have the mount drive.

.Steps
. Using Power Shell, connect to the IP address or fully qualified domain name of the Active IQ Unified Manager system.
. Log in to the system with the maintenance user (umadmin) name and password.
. Enter the command `maintenance_console` and press Enter.
. In the maintenance console *Main Menu*, enter the number for the *Backup Restore* option.
. Enter the number for *Configure NetApp Snapshot Backup*.
. Enter the number to configure iSCSI.
. Review the information that you will need to provide and then enter the number for *Enter Backup Configuration Details*.
. To identify the volume where the Snapshot will be written, enter the IP address of the Cluster Management interface, the name of the storage VM, the name of the volume, LUN name, the storage system user name and password, and the mount drive.
. Verify this information and enter `y`.
+
The system performs the following tasks:

 ** Storage VM is validated
 ** Volume is validated
 ** Mount drive and status is validated
 ** LUN existence and status
 ** Network drive existence
 ** Existence of recommend space (more than twice of mysql data directory) at mounted volume is validated
 ** LUN path corresponding to the dedicated LUN in the volume
 ** igroup name
 ** GUID of the volume where the network drive is mounted
 ** iSCSI initiator used to communicate with ONTAP

. Exit the maintenance console and launch the Active IQ Unified Manager interface to create a schedule for Snapshot copies.