---
permalink: health-checker/concept_monitoring_and_troubleshooting_data_availability.html
sidebar: sidebar
keywords: 
summary: 'Unified Manager monitors the reliability with which authorized users can access your stored data, alerts you to conditions that block or impede that access, and enables you to diagnose those conditions and assign and track their resolution.'
---
= Monitoring and troubleshooting data availability
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager monitors the reliability with which authorized users can access your stored data, alerts you to conditions that block or impede that access, and enables you to diagnose those conditions and assign and track their resolution.

The availability workflow topics in this section describe examples of how a storage administrator can use the Unified Manager web UI to discover, diagnose, and assign for resolution hardware and software conditions that adversely affect data availability.

*Related information*

xref:task_resolving_a_storage_failover_interconnect_link_down_condition.adoc[Scanning for and resolving storage failover interconnect link down conditions]

xref:task_resolving_volume_offline_issues.adoc[Resolving volume offline issues]
