---
permalink: health-checker/concept_configure_backup_for_linux.html
sidebar: sidebar
keywords: netapp, snapshot copy, copies, linux, operate, system, configure, backup
summary: "If your Active IQ Unified Manager is installed on a Linux machine, then you can decide to configure your backup and restore using NetApp Snapshots."
---
= Configure backup on Linux in Active IQ Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
If your Active IQ Unified Manager is installed on a Linux machine, then you can decide to configure your backup and restore using NetApp Snapshots.

Snapshot copies take very little time, usually just a few minutes, and the Unified Manager database is locked for a very short timeframe, so there is very little disruption to your installation. The image consumes minimal storage space and incurs negligible performance overhead because it records only changes to files since the last Snapshot copy was made. Because the Snapshot is created on an ONTAP cluster, you can take advantage of other NetApp features such as SnapMirror to create secondary protection, if needed.

Before beginning a backup operation, Unified Manager performs an integrity check to verify that the destination system is available.

[NOTE]
====

* You can restore a Snapshot copy only on the same version of Active IQ Unified Manager.
+
For example, if you created a backup on Unified Manager 9.18, the backup can be restored only on Unified Manager 9.18 systems.

* If there is any change in the Snapshot configuration, it might cause the snapshot to be invalid.

====
// 2025-6-10, ONTAPDOC-133
// 2025-7-10, OTHERDOC 152

== Configure Snapshot copy location in Active IQ Unified Manager

You can configure the volume where Snapshot copies will be stored on one of your ONTAP clusters using ONTAP System Manager or using the ONTAP CLI.

.Before you begin

The cluster, storage VM, and volume must meet the following requirements:

* Cluster requirements:
 ** ONTAP 9.3 or greater must be installed
 ** It should be geographically close to the Unified Manager server
 ** It can be monitored by Unified Manager, but it is not required
* Storage VM requirements:
 ** The name switch and name mapping must be set to use "`files`"
 ** Local users created to correspond with client-side users
 ** Make sure All Read/Write access is selected
 ** Make sure that Superuser Access is set to "`any`" in the export policy
 ** NFS for NetApp Snapshot for Linux
 ** NFSv4 must be enabled on the NFS server and NFSv4 ID domain specified on the client and storage VM
 ** The volume should be at least double the size of the Unified Manager/opt/netapp/data directory
+
Use the command du -sh /opt/netapp/data/ to check the current size.
* Volume requirements:
 ** The volume should be at least double the size of the Unified Manager /opt/netapp/data directory
 ** The security style must be set to UNIX
 ** The local snapshot policy must be disabled
 ** Volume autosize should be enabled
 ** The performance service level should be set to a policy with high IOPS and low latency, such as "`Extreme`"

For detailed steps to create the NFS volume, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode[How to configure NFSv4 in ONTAP 9] and the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html[ONTAP 9 NFS Configuration Express Guide].

== Specify the destination location for Snapshot copies in Active IQ Unified Manager

You should configure the destination location for Active IQ Unified Manager Snapshot copies on a volume that you have already configured in one of your ONTAP clusters. You should use maintenance console to define the location.

* You must have the root user credentials for the Linux host on which Active IQ Unified Manager is installed.
* You must have a user ID and password authorized to log in to the maintenance console of the Unified Manager server.
* You must have the Cluster Management IP address, the name of the storage VM, the name of the volume, and the storage system user name and password.
* You must have mounted the volume to the Active IQ Unified Manager host, and you must have the mount path.

.Steps
. Use Secure Shell to connect to the IP address or FQDN of the Active IQ Unified Manager system.
. Log in to the system with the maintenance user (umadmin) name and password.
. Enter the command `maintenance_console` and press Enter.
. In the maintenance console *Main Menu*, enter the number for the *Backup Restore* option.
. Enter the number for *Configure NetApp Snapshot Backup*.
. Enter the number to configure NFS.
. Review the information that you will need to provide and then enter the number for *Enter Backup Configuration Details*.
. To identify the volume where the Snapshot will be written, enter the IP address of the Cluster Management interface, the name of the storage VM, the name of the volume, LUN name, the storage system user name and password, and the mount path.
. Verify this information and enter `y`.
+
The system performs the following tasks:

 ** Establishes the connection to the cluster
 ** Stops all the services
 ** Creates a new directory in the volume and copies the Active IQ Unified Manager database configuration files
 ** Deletes the files from Active IQ Unified Manager and creates a symlink to the new database directory
 ** Restarts all the services

. Exit the maintenance console and launch the Active IQ Unified Manager interface to create a schedule for the Snapshot copy if you have not already done this.