---
permalink: health-checker/concept_manage_backup_and_restore_operations.html
sidebar: sidebar
keywords: backup, types, manage, restore, operations
summary: "You can create backups of Active IQ Unified Manager and use the restore feature to restore the backup to the same (local) system or a new (remote) system in case of a system failure or data loss."
---
= Manage backup and restore operations
:icons: font
:imagesdir: ../media/

[.lead]
You can create backups of Active IQ Unified Manager and use the restore feature to restore the backup to the same (local) system or a new (remote) system in case of a system failure or data loss.

There are three backup and restore methods depending on the operating system on which you have installed Unified Manager, and based on the number of clusters and nodes being managed:

[cols="3*",options="header"]
|===
| Operating System| Size of Deployment| Recommended Backup Method
a|
VMware vSphere
a|
Any
a|
VMware snapshot of the Unified Manager virtual appliance
.2+|
Red Hat Enterprise Linux 
a|
Small
a|
Unified Manager MySQL database dump
a|
Large
a|
NetApp Snapshot of Unified Manager database
.2+|
Microsoft Windows
a|
Small
a|
Unified Manager MySQL database dump
a|
Large
a|
NetApp Snapshot of Unified Manager database with iSCSI protocol
|===
These different methods are described in the sections that follow.

== Limitations to restore operations

You cannot perform a restore operation in any of the following scenarios:

* You are using an LDAP account.
* You are logged in as a domain user.
* Your account is configured for SAML authentication.
* You are using the NDMP protocol.

For more details, see the Knowledge Base article https://kb.netapp.com/on-prem/ontap/DP/NDMP/NDMP-KBs/How_to_configure_NDMP_authentication_in_the_SVM-scope_previously_known_as_Vserver-scope_mode[How to configure NDMP authentication in 'SVM-scope' mode]
====
// 2024-11-8, OTHERDOC87
// 2025-12-17, OTHERDOC 174