---
permalink: health-checker/task_view_details_about_cifs_shares.html
sidebar: sidebar
keywords: smb, cifs, view, shares, details
summary: "You can view details about all SMB/CIFS shares, such as the share name, junction path, containing objects, security settings, and export policies defined for the share. Use the Health: All SMB Shares view to see all SMB shares on all monitored clusters, and use the Storage VM / Health details page to view all SMB shares on a specific storage virtual machine (SVM)."
---
= Viewing details about SMB/CIFS shares
:icons: font
:imagesdir: ../media/

[.lead]
You can view details about all SMB/CIFS shares, such as the share name, junction path, containing objects, security settings, and export policies defined for the share. Use the Health: All SMB Shares view to see all SMB shares on all monitored clusters, and use the Storage VM / Health details page to view all SMB shares on a specific storage virtual machine (SVM).

*What you'll need*

* CIFS license must be enabled on the cluster.
* Network interfaces serving the SMB/CIFS shares must be configured.
* You must have the Operator, Application Administrator, or Storage Administrator role.

[NOTE]
====
Shares in folders are not displayed.
====

.Step

. In the left navigation pane, follow the steps below depending on whether you want to view all SMB/CIFS shares or just the shares for a particular SVM.
+
[cols="2*",options="header"]
|===
| To...| Follow these steps...
a|
View all SMB/CIFS shares
a|
Click *Storage* > *SMB Shares*
a|
View SMB/CIFS shares for single SVM
a|

 .. Click *Storage* > *Storage VMs*
 .. Click the SVM for which you want to view the SMB/CIFS share details.
 .. In the Storage VM / Health details page, click the *SMB Shares* tab.

+
|===

For more information, see link:../api-automation/concept_provision_file_share.html[Provisioning CIFS and NFS file shares by using APIs].