---
permalink: health-checker/task_edit_individual_aggregate_health_threshold_settings.html
sidebar: sidebar
keywords: edit, individual, aggregate, health, threshold, settings
summary: "You can edit the health threshold settings for aggregate capacity, growth, and Snapshot copies of one or more aggregates. When a threshold is crossed, alerts are generated and you receive notifications. These notifications help you to take preventive measures based on the event generated."
---
= Editing individual aggregate health threshold settings
:icons: font
:imagesdir: ../media/

[.lead]
You can edit the health threshold settings for aggregate capacity, growth, and Snapshot copies of one or more aggregates. When a threshold is crossed, alerts are generated and you receive notifications. These notifications help you to take preventive measures based on the event generated.

*What you'll need*

You must have the Application Administrator or Storage Administrator role.

Based on changes to the threshold values, events are generated or obsoleted in the next monitoring cycle.

When Autogrow is enabled on volumes that reside on the aggregate, the aggregate capacity thresholds are considered breached based on the maximum volume size set by autogrow, not based on the original volume size.

.Steps
. In the left navigation pane, click *Storage* > *Aggregates*.
. In the *Health: All Aggregates* view, select one or more aggregates and then click *Edit Thresholds*.
. In the *Edit Aggregate Thresholds* dialog box, edit the threshold settings of one of the following: capacity, growth, or Snapshot copies by selecting the appropriate check box and then modifying the settings.
. Click *Save*.

*Related information*

link:../config/task_add_users.html[Adding users]
