---
permalink: health-checker/task_add_group_rules.html
sidebar: sidebar
keywords: add, group rules
summary: "You can create group rules for a group to dynamically add storage objects such as volumes, clusters, or storage virtual machines (SVMs) to the group. You must configure at least one condition group with at least one condition to create a group rule."
---
= Adding group rules
:icons: font
:imagesdir: ../media/

[.lead]
You can create group rules for a group to dynamically add storage objects such as volumes, clusters, or storage virtual machines (SVMs) to the group. You must configure at least one condition group with at least one condition to create a group rule.

*What you'll need*

You must have the Application Administrator or Storage Administrator role.

Storage objects that are currently monitored are added as soon as the group rule is created. New objects are added only after the monitoring cycle is completed.

.Steps
. In the left navigation pane, click *Storage Management* > *Groups*.
. In the *Group Rules* tab, click *Add*.
. In the *Add Group Rule* dialog box, specify a name for the group rule.
. In the *Target Object Type* field, select the type of storage object that you want to group.
. In the *Group* field, select the required group for which you want to create group rules.
. In the *Conditions* section, perform the following steps to create a condition, a condition group, or both:
+
[cols="2*",options="header"]
|===
| To create....| Do this...
a|
A condition
a|

 .. Select an operand from the list of operands.
 .. Select either *Contains* or *Is* as the operator.
 .. Enter a value, or select a value from the available list.

a|
A condition group
a|

 .. Click *Add Condition Group*
 .. Select an operand from the list of operands.
 .. Select either *Contains* or *Is* as the operator.
 .. Enter a value, or select a value from the available list.
 .. Click *Add condition* to create more conditions if required, and repeat steps a through d for each condition.

+
|===

. Click *Add*.

== Example for creating a group rule

Perform the following steps in the Add Group Rule dialog box to create a group rule, including configuring a condition and adding a condition group:

.Steps
. Specify a name for the group rule.
. Select the object type as storage virtual machine (SVM).
. Select a group from the list of groups.
. In the Conditions section, select *Object Name* as the operand.
. Select *Contains* as the operator.
. Enter the value as `svm_data`.
. Click *Add condition group*.
. Select *Object Name* as the operand.
. Select *Contains* as the operator.
. Enter the value as `vol`.
. Click *Add condition*.
. Repeat steps 8 through 10 by selecting *data-priority* as the operand in step 8, *Is* as the operator in step 9, and *critical* as the value in step 10.
. Click *Add* to create the condition for the group rule.
