---
permalink: health-checker/task_view_aggregate_list_and_details.html
sidebar: sidebar
keywords: view, aggregate list, details
summary: "From the Health: All Aggregates view, you can monitor your inventory of aggregates. The Capacity: All Aggregates view enables you to view information about the capacity and utilization of aggregates in all clusters."
---
= Viewing the aggregate list and details
:icons: font
:imagesdir: ../media/

[.lead]
From the Health: All Aggregates view, you can monitor your inventory of aggregates. The Capacity: All Aggregates view enables you to view information about the capacity and utilization of aggregates in all clusters.

*What you'll need*

You must have the Operator, Application Administrator, or Storage Administrator role.

You can view details such as aggregate capacity and configuration, and disk information from the Aggregate / Health details page. You can use these details before you configure the threshold settings if required.

.Steps
. In the left navigation pane, click *Storage* > *Aggregates*.
. Choose one of the following ways to view the aggregate details:
 ** To view information about the health of all aggregates in all clusters, in the View menu, select Health: All Aggregates view.
 ** To view information about the capacity and utilization of all aggregates in all clusters, in the View menu, select Capacity: All Aggregates view.
 ** To view the complete details, click the aggregate name.
+
You can also view the complete details by clicking *View Details* in the minimal details dialog box.
. View the objects related to the aggregate by clicking *View Related* from the minimal details dialog box.

*Related information*

* link:../health-checker/reference_health_aggregate_details_page.html[Aggregate / Health details page]
* link:../performance-checker/performance-view-all.html#performance-all-aggregates-view[Performance: All Aggregates view]
* link:../reporting/concept_customize_aggregate_capacity_reports.html[Customizing aggregate capacity reports]
