---
permalink: health-checker/task_determine_if_volume_is_offline_because_of_broken_disks.html
sidebar: sidebar
keywords: determine, volume, offline, broken disks, aggregate
summary: "You can use the Unified Manager web UI to confirm or eliminate the possibility that a volume is offline because RAID disk problems have taken its host aggregate offline."
---
= Determining if a volume is offline because of broken disks in an aggregate
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Unified Manager web UI to confirm or eliminate the possibility that a volume is offline because RAID disk problems have taken its host aggregate offline.

*What you'll need*

You must have the Operator, Application Administrator, or Storage Administrator role.

To determine if the volume offline condition is caused by RAID disk problems that are taking the hosting aggregate offline, perform the following actions:

.Steps
. Locate and click the hypertext link displayed under Aggregate in the *Related Devices* pane of the *Volume / Health* details page.
+
The Aggregate / Health details page displays the online or offline status of the hosting aggregate. If the aggregate status is online, then RAID disk problems are not the cause of the volume being offline.

. If the aggregate status is offline, then click *Disk Information* and look for broken disk events in the *Events* list on the *Disk Information* tab.
. To further identify the broken disks, click the hypertext link displayed under Node in the *Related Devices* pane.
+
The Cluster / Health details page is displayed.

. Click *Disks*, and then select *Broken* in the *Filters* pane to list all disks in the broken state.
+
If the disks in the broken state caused the offline state of the host aggregate, the name of the aggregate is displayed in the Impacted Aggregate column.

After confirming that the volume offline condition is caused by broken RAID disks and the consequent offline host aggregate, contact the appropriate administrator or operator to manually replace the broken disks and put the aggregate back online.
