---
permalink: health-checker/task_generate_hardware_inventory_report_for_contract_renewal.html
sidebar: sidebar
keywords: contract, renewal, cluster, inventory report, hardware, generate
summary: "You can generate a report that contains a complete list of cluster and node information; such as hardware model numbers and serial numbers, disk types and counts, installed licenses, and more. This report is helpful for contract renewal within secure sites (“dark” sites) that are not connected to the NetAppActive IQ platform."
---
= Generating a hardware inventory report for contract renewal
:icons: font
:imagesdir: ../media/

[.lead]
You can generate a report that contains a complete list of cluster and node information; such as hardware model numbers and serial numbers, disk types and counts, installed licenses, and more. This report is helpful for contract renewal within secure sites ("`dark`" sites) that are not connected to the NetAppActive IQ platform.

*What you'll need*

You must have the Operator, Application Administrator, or Storage Administrator role.

.Steps
. In the left navigation pane, click *Storage* > *Nodes*.
. Go to the *Health: All Nodes* view or *Performance: All Nodes* view.
. Select *Reports* > *** > **Hardware Inventory Report*.
+
The hardware inventory report is downloaded as a .csv file with complete information as of the current date.

. Provide this information to your NetApp support contact for contract renewal.
