---
permalink: health-checker/task_specify_destination_location_for_snapshot_backups.html
sidebar: sidebar
keywords: specify, destination location, snapshot copies, copy
summary: "You should configure the destination location for Active IQ Unified Manager Snapshot copies on a volume that you have already configured in one of your ONTAP clusters. You should use maintenance console to define the location."
---
= Specifying the destination location for Snapshot copies
:icons: font
:imagesdir: ../media/

[.lead]
You should configure the destination location for Active IQ Unified Manager Snapshot copies on a volume that you have already configured in one of your ONTAP clusters. You should use maintenance console to define the location.

* You must have the root user credentials for the Linux host on which Active IQ Unified Manager is installed.
* You must have a user ID and password authorized to log in to the maintenance console of the Unified Manager server.
* You must have the Cluster Management IP address, the name of the storage VM, the name of the volume, and the storage system user name and password.
* You must have mounted the volume to the Active IQ Unified Manager host, and you must have the mount path.

.Steps
. Use Secure Shell to connect to the IP address or FQDN of the Active IQ Unified Manager system.
. Log in to the system with the maintenance user (umadmin) name and password.
. Enter the command `maintenance_console` and press Enter.
. In the maintenance console *Main Menu*, enter the number for the *Backup Restore* option.
. Enter the number for *Configure NetApp Snapshot Backup*.
. Enter the number to configure NFS.
. Review the information that you will need to provide and then enter the number for *Enter Backup Configuration Details*.
. To identify the volume where the Snapshot will be written, enter the IP address of the Cluster Management interface, the name of the storage VM, the name of the volume, LUN name, the storage system user name and password, and the mount path.
. Verify this information and enter `y`.
+
The system performs the following tasks:

 ** Establishes the connection to the cluster
 ** Stops all the services
 ** Creates a new directory in the volume and copies the Active IQ Unified Manager database configuration files
 ** Deletes the files from Active IQ Unified Manager and creates a symlink to the new database directory
 ** Restarts all the services

. Exit the maintenance console and launch the Active IQ Unified Manager interface to create a schedule for the Snapshot copy if you have not already done this.
