---
permalink: health-checker/task_viewing_all_security_events.html
sidebar: sidebar
keywords: view security events
summary: 'You can view all the active security events and then assign each of them to a user who can resolve the issue. Additionally, if there are certain security events that you do not want to receive, this list can help you identify the events that you want to disable.'
---
= Viewing all active security events
:icons: font
:imagesdir: ../media/

[.lead]
You can view all the active security events and then assign each of them to a user who can resolve the issue. Additionally, if there are certain security events that you do not want to receive, this list can help you identify the events that you want to disable.

You must have the Operator, Application Administrator, or Storage Administrator role.

. In the left navigation pane, click *Event Management*.
+
By default, New and Acknowledged events are displayed on the Event Management inventory page.

. From the View menu, select *Active security events*.
+
The page displays all New and Acknowledged Security events that have been generated in the past 7 days.

*Related information*

xref:task_adding_alerts_for_security_events.adoc[Adding alerts for security events]

xref:task_disabling_specific_security_events.adoc[Disabling specific security events]
