---
permalink: health-checker/task_edit_group_actions.html
sidebar: sidebar
keywords: 
summary: 'You can edit the group action parameters that you configured in Unified Manager, such as the group action name, description, associated group name, and parameters of the action type.'
---
= Editing group actions
:icons: font
:imagesdir: ../media/

[.lead]
You can edit the group action parameters that you configured in Unified Manager, such as the group action name, description, associated group name, and parameters of the action type.

You must have the Application Administrator or Storage Administrator role.

. In the left navigation pane, click *Storage Management* > *Groups*.
. In the Group Actions tab, select the group action that you want to edit, and then click *Edit*.
. In the Edit Group Action dialog box, change the group action name, description, associated group name, and parameters of the action type, as required.
. Click *Save*.

*Related information*

xref:concept_manage_and_monitor_groups.adoc[Managing and monitoring groups]

xref:task_add_group_actions.adoc[Adding group actions]

xref:task_delete_group_actions.adoc[Deleting group actions]
