---
permalink: health-checker/task_restore_snapshot_backup.html
sidebar: sidebar
keywords: restore, linux, snapshot, backup, windows
summary: "If data loss or data corruption occurs, you can restore Unified Manager to the previous stable state with minimum loss of data. You can restore the Unified Manager Snapshot database to a local or remote operating system by using the Unified Manager maintenance console."
---
= Restoring a Snapshot backup for Linux and Windows
:icons: font
:imagesdir: ../media/

[.lead]
If data loss or data corruption occurs, you can restore Unified Manager to the previous stable state with minimum loss of data. You can restore the Unified Manager Snapshot database to a local or remote operating system by using the Unified Manager maintenance console.

*What you'll need*

* You must have the root user credentials for the Linux host and administrative privileges for Windows host machine on which Unified Manager is installed.
* You must have a user ID and password authorized to log in to the maintenance console of the Unified Manager server.

The restore feature is platform-specific and version-specific. You can restore a Unified Manager backup only on the same version of Unified Manager.

.Steps
. Connect to the IP address or fully qualified domain name of the Unified Manager system.
+
|===
    a|
*Linux*
a|
Secure Shell
a|
*Windows*
a|
Power Shell
|===

. Log in to the system with the root user credentials.
. Enter the command `maintenance_console` and press Enter.
. In the maintenance console *Main Menu*, enter the number for the *Backup Restore* option.
. Enter the number for *Backup and Restore using NetApp Snapshot*.
+
If you are performing a restore onto a new server, after installing Unified Manager do not launch the UI or configure any clusters, users, or authentication settings when the installation is complete. Enter the number for *Configure NetApp Snapshot Backup* and configure the Snapshot backup settings as they were configured on the original system.

. Enter the number for *Restore using NetApp Snapshot*.
. Select the Snapshot backup file that you want to restore and press *Enter*.
. After the restore process is complete, log in to the Unified Manager user interface.

After you restore the backup, if the Workflow Automation server does not work, perform the following steps:

. On the Workflow Automation server, change the IP address of the Unified Manager server to point to the latest machine.
. On the Unified Manager server, reset the database password if the acquisition fails in step 1.
