---
permalink: health-checker/task_view_antiransomware_status_of_all_volumes.html
sidebar: sidebar
keywords: view, anti-ransomware status, volumes
summary: "You can view a list of all the volumes and their current anti-ransomware status so you can determine whether the data on your volumes is adequately protected from ransomware attacks."
---
= Viewing the anti-ransomware status of all volumes
:icons: font
:imagesdir: ../media/

[.lead]
You can view a list of all the volumes and their current anti-ransomware status so you can determine whether the data on your volumes is adequately protected from ransomware attacks.

*What you'll need*

You must have the Operator, Application Administrator, or Storage Administrator role.

Volumes can have the following anti-ransomware statuses:

* Disabled
* Disabling
* Enabled (Learning mode)
* Enabled (Active mode)
* Paused (Active mode)
* Paused (Learning mode)

For more information on the different anti-ransomware statuses, see link:https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html#system-manager-procedure[ONTAP: Enable anti-ransomware].

.Steps
. In the left navigation pane, click *Storage* > *Volumes*.
. In the View menu, select *Health* > *Security* > *Anti-ransomware*
. In the *Security: Anti-ransomware* view, you can sort by the various fields or use the Filter.

NOTE: Anti-ransomware is not supported for offline volumes, restricted volumes, Snaplock volumes, FlexGroup volumes, FlexCache volumes, SAN-only volumes, volumes of stopped storage VMs, root volumes of storage VMs, or data protection volumes.
