---
permalink: health-checker/task_retrieve_support_bundle_using_unix_or_linux_client.html
sidebar: sidebar
keywords: retrieve, support bundle, unix, linux, client
summary: "If you are a UNIX or Linux user, you can retrieve the support bundle from your vApp by using the command-line interface (CLI) on your Linux client server. You can use either SCP or SFTP to retrieve the support bundle."
---
= Retrieving the support bundle using a UNIX or Linux client
:icons: font
:imagesdir: ../media/

[.lead]
If you are a UNIX or Linux user, you can retrieve the support bundle from your vApp by using the command-line interface (CLI) on your Linux client server. You can use either SCP or SFTP to retrieve the support bundle.

*What you'll need*

You must be the maintenance user to perform this task.

You must have generated a support bundle using the maintenance console and have the support bundle name available.

.Steps
. Access the CLI through Telnet or the console, using your Linux client server.
. Access the /`support` directory.
. Retrieve the support bundle and copy it to the local directory using the following command:
+
[cols="2*",options="header"]
|===
| If you are using...| Then use the following command...
a|
SCP
a|
`scp <maintenance-user>@<vApp-name-or-ip>:/support/support_bundle_file_name.7z <destination-directory>`
a|
SFTP
a|
`sftp <maintenance-user>@<vApp-name-or-ip>:/support/support_bundle_file_name.7z <destination-directory>`
|===
The name of the support bundle is provided to you when you generate it using the maintenance console.

. Enter the maintenance user password.

== Examples

The following example uses SCP to retrieve the support bundle:

----

        `$ scp admin@10.10.12.69:/support/support_bundle_20160216_145359.7z .`
Password: `<maintenance_user_password>`
support_bundle_20160216_145359.7z   100%  119MB  11.9MB/s   00:10
----

The following example uses SFTP to retrieve the support bundle:

----

        `$ sftp admin@10.10.12.69:/support/support_bundle_20160216_145359.7z .`
Password: `<maintenance_user_password>`
Connected to 10.228.212.69.
Fetching /support/support_bundle_20130216_145359.7z to ./support_bundle_20130216_145359.7z
/support/support_bundle_20160216_145359.7z
----
