---
permalink: install-vapp/task_download_unified_manager_ova_file.html
sidebar: sidebar
keywords: download, unified manager, installation, file
summary: "Download the Unified Manager installation file from the NetApp Support Site to deploy Unified Manager as a virtual appliance."
---
= Downloading the Unified Manager installation file
:icons: font
:imagesdir: ../media/

[.lead]
Download the Unified Manager installation file from the NetApp Support Site to deploy Unified Manager as a virtual appliance.

*What you'll need*

You should have the login credentials for the NetApp Support Site.

The installation file is an `OVA` file that contains the Unified Manager software configured in a virtual appliance.

.Steps

. Log in to the NetApp Support Site, and navigate to the Download page for Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab[NetApp Support Site]
. Select the required version of Unified Manager and accept the end-users license agreement (EULA).
. Download and save the `OVA` file for VMware VSphere installation to a local directory or network directory that is accessible to your vSphere Client.
. Verify the checksum to ensure that the software downloaded correctly.
