---
permalink: install-vapp/task_restart_unified_manager_virtual_machine.html
sidebar: sidebar
keywords: restart, unified manager, virtual, machine
summary: "You can restart the Unified Manager virtual machine (VM) from the maintenance console. You should restart the VM after generating a new security certificate, or if there is a problem with the VM."
---
= Restart the Unified Manager virtual machine
:icons: font
:imagesdir: ../media/

[.lead]
You can restart the Unified Manager virtual machine (VM) from the maintenance console. You should restart the VM after generating a new security certificate, or if there is a problem with the VM.

.Before you begin

* The virtual appliance should be powered on.
* You should be logged in to the Unified Manager maintenance console as the maintenance user.

You can also restart the virtual machine from vSphere by using the VMware *Restart Guest* option. Refer to https://developer.broadcom.com/powercli/latest/vmware.vimautomation.core/commands/restart-vmguest/[the Restart-VMGuest cmdlet in Broadcom's VMware vSphere PowerCLI CMDLET reference.^]

.Steps

. In the maintenance console, select *System Configuration* > *Reboot Virtual Machine*.
. Start the Unified Manager web UI from your browser, and log in.

// 2025-6-11, OTHERDOC-133
// 2025-21-7, GitHub issue 59