---
permalink: install-windows/qsg-windows.html
sidebar: sidebar
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer
summary: "Quick start guide for Unified Manager on Windows platform."
---
= Quick start instructions for Windows installations
:icons: font
:imagesdir: ../media/

[.lead]
You can download the installation package and install Unified Manager to monitor and troubleshoot data storage capacity, availability, performance, and protection issues.

== System requirements

* Operating Systems
** Microsoft Windows Server 2019 Standard and Datacenter Edition
** Microsoft Windows Server 2022 Standard and Datacenter Edition
+
Unified Manager is supported on 64 bits Windows operating system for the following languages:
 ** English
 ** Japanese
 ** Simplified Chinese
*	RAM: 12 GB
*	CPU: 9572 MHz total
*	Free disk space: 100 GB of disk space for the installation directory, 50 GB of disk space for the MySQL data directory

For detailed system requirements, see the link:../install-windows/concept_requirements_for_installing_unified_manager.html[Requirements for installing Unified Manager] and link:http://mysupport.netapp.com/matrix[Interoperability Matrix^].

== Installing Active IQ Unified Manager

=== Download the installer
.	Download the `ActiveIQUnifiedManager-<version>.exe` installation package.
.	Copy the installation file to a directory on the target system.

=== Install Unified Manager
For installing Unified Manager, ensure that you have Microsoft .NET 4.5.2, or a later version installed. As a part of the installation process, Unified Manager installs other third-party packages as required. For more information about the dependent software packages, refer to the link:../install-windows/reference_windows_software_and_installation_requirements.html[Windows software and installation requirements].

.	Log in to Windows using the default local administrator account.
.	In the directory where you downloaded the installation file, right-click and run the Unified Manager executable (.exe) file as an administrator.
.	When prompted, enter the user name and password to create the Unified Manager maintenance user.
.	In the Database Connection wizard, enter the MySQL root password.
.	Follow the remaining prompts to complete the installation.
.	Click *Finish* at the end of the installation and the Unified Manager web UI is displayed.
