---
permalink: install-windows/task_upgrade_openjdk_on_windows_ocum.html
sidebar: sidebar
keywords: openjdk, jre, upgrade
summary: "You can upgrade to a newer version of OpenJDK on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities."
---
= Upgrade OpenJDK
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade to a newer version of OpenJDK on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.

.Before you begin

You must have Windows admin privileges for the system on which Unified Manager is installed.

You can update OpenJDK releases within release families. For example, you can upgrade from OpenJDK 11.0.16 to OpenJDK 11.0.18, but you cannot update directly from OpenJDK 11 to OpenJDK 12.

.Steps

. Log in as the admin user on the Unified Manager host machine.
. Download the appropriate version of OpenJDK (64-bit) from the OpenJDK site to the target system.
+
For example, download the `jdk-17.0.15_windows-x64_bin.zip` file from link:https://www.oracle.com/java/technologies/javase/jdk17-0-13-later-archive-downloads.html[the Oracle Java SE 17 Archive Downloads page^].
+
[NOTE]
 An Oracle account is required to download the file. If you do not have an Oracle account, go to link:https://signon.oracle.com/signin[Oracle account sign in] page to create one. 


. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp Active IQ Acquisition Service (Ocie-au)
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
. Expand the `zip` file.
. Copy the directories and files from the resulting `jdk` directory (for example, `jdk-11.0.18` to the location where Java is installed. Example: `C:\Program Files\NetApp\JDK\`
. Start the Unified Manager services by using the Windows Services console:
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
 ** NetApp Active IQ Acquisition Service (Ocie-au)
// 2025-6-11, OTHERDOC-133
// 2025-10-10, OTHERDOC -152
// 2025-10-23, OTHERDOC - 162