---
permalink: install-windows/task_change_jboss_password_on_windows.html
sidebar: sidebar
keywords: change, jboss, password
summary: "You can reset the instance-specific JBoss password that is set during installation. You can reset the password optionally, in case your site requires this security capability to override the Unified Manager installation setting. This operation also changes the password JBoss uses to access MySQL."
---
= Changing the JBoss password
:icons: font
:imagesdir: ../media/

[.lead]
You can reset the instance-specific JBoss password that is set during installation. You can reset the password optionally, in case your site requires this security capability to override the Unified Manager installation setting. This operation also changes the password JBoss uses to access MySQL.

*What you'll need*

* You should have Windows admin privileges for the system on which Unified Manager is installed.
* You should have the password for the MySQL root user.
* You should be able to access the NetApp-provided `password.bat` script in the directory
+
`C:\Program Files\NetApp\essentials\bin`.

.Steps

. Log in as the admin user on the Unified Manager host machine.
. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp Active IQ Acquisition Service (Ocie-au)
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
. Launch the `password.bat` script to begin the password change process:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. When prompted, enter the MySQL root user password.
. When prompted, enter the new JBoss user password, and then enter it again for confirmation.
+
Note that the password should be between 8 and 16 characters, and must contain at least a digit, an upper case and lower case characters, and at least one of these special characters:
+
`+!@%^*-_+=[]:<>.?/~+`

. When the script completes, start the Unified Manager services by using the Windows Services console:
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
 ** NetApp Active IQ Acquisition Service (Ocie-au)
. After all of the services are started, you can log in to the Unified Manager UI.
