---
permalink: install-windows/task_uninstall_unified_manager_win.html
sidebar: sidebar
keywords: uninstall, unified manager
summary: "You can uninstall Unified Manager by using the Programs and Features wizard, or by performing an unattended uninstallation from the command-line interface."
---
= Uninstalling Unified Manager
:icons: font
:imagesdir: ../media/
:pp: {plus}{plus}

[.lead]
You can uninstall Unified Manager by using the Programs and Features wizard, or by performing an unattended uninstallation from the command-line interface.

*What you'll need*

* You must have Windows administrator privileges.
* All clusters (data sources) must be removed from the Unified Manager server before uninstalling the software.
* You should manually delete the firewall rules that are created to allow or block MySQL port 3306. The firewall rules are not deleted automatically.

.Steps

. Uninstall Unified Manager by choosing one of the following options:
** If you uninstall Unified Manager from *Programs and Features* wizard, perform these steps:
.. Navigate to *Control Panel* > *Program and Features*.
.. Select Active IQ Unified Manager, and click *Uninstall*.
** If you uninstall Unified Manager from Command line, then perform these steps:
.. Log in to the Windows command line using administrator privileges.
.. Navigate to the Active IQ Unified Manager directory, and run the following command:
+
`+msiexec /x {A78760DB-7EC0-4305-97DB-E4A89CDFF4E1} /qn /l*v %systemdrive%\UmUnInstall.log+`
+
If User Account Control (UAC) is enabled on the server, and you are logged in as a domain user, you must use the command-line uninstallation method.
+
Unified Manager is uninstalled from your system.

. Uninstall the following third-party packages and data that are not removed during the Unified Manager uninstallation:
 ** Third-party packages: JRE, MySQL, Microsoft Visual C{pp} 2015 Redistributable, Python, and 7zip
 ** MySQL application data generated by Unified Manager
 ** Application logs and contents of application data directory
