---
permalink: install-windows/task_install_unified_manager_on_windows.html
sidebar: sidebar
keywords: install, unified manager
summary: "You can install Unified Manager to monitor and troubleshoot data storage capacity, availability, performance, and protection issues."
---
= Installing Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can install Unified Manager to monitor and troubleshoot data storage capacity, availability, performance, and protection issues.

*What you'll need*

* The system on which you plan to install Unified Manager should meet the system and software requirements.
+
See link:concept_virtual_infrastructure_or_hardware_system_requirements.html[Hardware system requirements].
+
See link:reference_windows_software_and_installation_requirements.html[Windows software and installation requirements].
+
[NOTE]
====
Starting with Unified Manager 9.5, OpenJDK is provided in the installation package and installed automatically. Oracle Java is not supported starting with Unified Manager 9.5.
====

* You should have Windows administrator privileges. Ensure that your user name does not begin with an exclamation mark "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!`".
* You should have a supported web browser.
* The Unified Manager maintenance user password should be between 8 and 20 characters, should contain upper-case letters or lower-case letters, numerals, and special characters.
* The following special characters are not allowed in the password string for the maintenance user or for the MySQL root user: " ' ` % , = & < > | {caret} \ / ( ) [ ] ;:
+
The following special characters are allowed: ~ ! @ # $ * - ? . + { }

.Steps

. Log in to Windows using the default local administrator account.
. Log in to the NetApp Support Site, and navigate to the Download page for Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab[NetApp Support Site^]
. Select the required version of Unified Manager and accept the end-users license agreement (EULA).
. Download the Unified Manager Windows installation file to a target directory on the Windows system.
. Navigate to the directory where the installation file is located.
. Right-click and run the Unified Manager installer executable (.exe) file as an administrator.
+
Unified Manager detects missing or pre-installed third-party packages and lists them. If the required third-party packages are not installed in the system, Unified Manager installs them as part of the installation.

. Click *Next*.
. Enter the user name and password to create the maintenance user.
. In the Database Connection wizard, enter the MySQL root password.
. Click *Change* to specify a new location for the Unified Manager installation directory and MySQL data directory.
+
If you do not change the installation directory, Unified Manager is installed in the default installation directory.

. Click *Next*.
. In the Ready to Install Shield wizard, click *Install*.
. After the installation is complete, click *Finish*.
. If you have an active anti-virus software installed on your Windows system, manually exclude the following paths from anti-virus scan after your installation is complete:

* Unified Manager data directory
* Unified Manager installation directory
* MySQL data directory

The installation creates multiple directories:

* Installation directory
+
This is the root directory for Unified Manager, which you specified during installation. Example: `C:\Program Files\NetApp\`

* MySQL data directory
+
This is the directory where the MySQL databases are stored, which you specified during installation. Example: `C:\ProgramData\MySQL\MySQLServerData\`

* Java directory
+
This is the directory where OpenJDK is installed. Example: `C:\Program Files\NetApp\JDK\`

* Unified Manager application data directory (appDataDir)
+
This is the directory where all the application-generated data is stored. This includes logs, support bundles, backup, and all other additional data. Example: `C:\ProgramData\NetApp\OnCommandAppData\`

You can access the web UI to perform the initial setup of Unified Manager, as described in the link:../config/concept_configure_unified_manager.html[Configuring Active IQ Unified Manager].
