---
permalink: install-windows/task_upgrade_to_unified_manager_on_microsoft_windows.html
sidebar: sidebar
keywords: upgrade, unified manager
summary: "You can upgrade Unified Manager by downloading and running the installation file on the Windows platform."
---
= Upgrading Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade Unified Manager 9.11 or 9.12 to 9.13 by downloading and running the installation file on the Windows platform.

*What you'll need*

* The system on which you are upgrading Unified Manager should meet the system and software requirements.
+
See link:concept_virtual_infrastructure_or_hardware_system_requirements.html[Hardware system requirements].
+
See link:reference_windows_software_and_installation_requirements.html[Windows software and installation requirements].
+
[NOTE]
====
Starting with Unified Manager 9.5, OpenJDK is provided in the installation package and installed automatically. Oracle Java is not supported starting with Unified Manager 9.5.
====
+
[NOTE]
====
Ensure that Microsoft .NET 4.5.2 or greater is installed on your system before starting the upgrade.
====

* MySQL Community Edition is automatically upgraded during Unified Manager upgrade. If the installed version of MySQL on your system is earlier than 8.0.32, the Unified Manager upgrade process automatically upgrades MySQL to 8.0.32. You must not run a standalone upgrade of an earlier version of MySQL to 8.0.32.
* You should have Windows administrator privileges. Ensure that your user name does not begin with an exclamation mark "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!`".
* You should have valid credentials to log in to the NetApp Support Site.
* To avoid data loss, you should have created a backup of the Unified Manager machine in case there is an issue during the upgrade.
* You should have adequate disk space available to perform the upgrade.
+
The available space on the installation drive should be 2.5 GB larger than the size of the data directory. The upgrade stops and displays an error message indicating the amount of space to be added if there is not enough free space.

* During upgrade, you may be prompted to confirm whether you want to keep the previous, default settings for retaining performance data for 13 months or to change it to 6 months. On confirming, the historical performance data after 6 months is purged.
* Before upgrading, you should close any open files or folder in _<InstallDir>\JDK_ and _MySQL Data Directory_.
* If you have an active anti-virus software installed on your Windows system, Unified Manager upgrade might fail. You should disable all virus scan software on your system before upgrading Unified Manager.

During the upgrade process, Unified Manager is unavailable. You should complete any running operations before upgrading Unified Manager.

If Unified Manager is paired with an instance of OnCommand Workflow Automation, and there are new versions of software available for both products, you must disconnect the two products and then set up a new Workflow Automation connection after performing the upgrades. If you are performing an upgrade to only one of the products, then you should log into Workflow Automation after the upgrade and verify that it is still acquiring data from Unified Manager.

.Steps

. Log in to the NetApp Support Site, and navigate to the Download page for Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab[NetApp Support Site^].
. Select the required version of Unified Manager and accept the end-users license agreement (EULA).
. Download the Unified Manager Windows installation file to a target directory on the Windows system.
. Right-click and run the Unified Manager installer executable (.exe) file as an administrator.
+
Unified Manager prompts you with the following message:
+
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----

. Click *Yes*, and then click *Next*.
. Enter the MySQL8 root password that was set during installation, and then click *Next*.
. Launch the web UI on a new window on a supported web browser and log in to use the upgraded version of Unified Manager.
. If you have an active anti-virus software installed on your Windows system, make sure to manually exclude the following paths from anti-virus scan after your upgrade is complete:

* Unified Manager data directory
* Unified Manager installation directory
* MySQL data directory

[NOTE]
====
To perform a silent upgrade of Unified Manager, run the following command:
`ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=<password> /qn /l*v <system_drive>:\install.log"`
====
