---
permalink: config/concept_maintenance_console_menu.html
sidebar: sidebar
keywords: maintenance, console, menus
summary: "The maintenance console consists of different menus that enable you to maintain and manage special features and configuration settings of the Unified Manager server."
---
= Maintenance console menus
:icons: font
:imagesdir: ../media/

[.lead]
The maintenance console consists of different menus that enable you to maintain and manage special features and configuration settings of the Unified Manager server.

Depending on the operating system on which you have installed Unified Manager, the maintenance console consists of the following menus:

* Upgrade Unified Manager (VMware only)
* Network Configuration (VMware only)
* System Configuration (VMware only)

. Support/Diagnostics
. Reset Server Certificate
. External Data Provider
. Backup Restore
. Performance Polling Interval Configuration
. Disable SAML authentication
. View/Change Application Ports
. Debug Log Configuration
. Control access to MySQL port 3306
. Exit

You select the number from the list for accessing the specific menu option. For example, for backup and restore, you select _4_.
