---
permalink: config/concept_security_dashboard.html
sidebar: sidebar
keywords: enabling security dashboard, security feature settings, security features, ONTAP hardening guide
summary: "You can enable or disable the Security panel on the Active IQ Unified Manager dashboard. When enabled, you can also customize the settings for compliance monitoring and the relevant security events and management actions."
---
= Enabling security settings on Security Dashboard
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable the security settings on the Security panel on the Active IQ Unified Manager dashboard. By modifying these feature settings, you can customize the settings for compliance monitoring and the relevant security events and management actions.

[NOTE]
====
Only users with administrator role can edit these settings.
====

The security criteria for your ONTAP clusters, storage VMs, and volumes are evaluated against the recommendations defined in the link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf[Security Hardening Guide for NetApp ONTAP 9]. The Security panel on the dashboard displays the default security compliance status of your clusters, storage VMs, and volumes. Security events are also generated for the clusters and storage VMs that have security violations.

== Customizing settings

From  can customize the settings for compliance monitoring as applicable to your ONTAP environment. These settings trigger the relevant security events and management actions. Follow these steps:

. Click *General > Feature Settings > Security Dashboard > Customize*. The Customize Security Dashboard Settings pop-up appears.

+

[NOTE]
====
The security compliance parameters that you enable or disable can directly affect the default view, reports, and scheduled reports on the Clusters and Storage VMs screens. If you had uploaded an excel report from these screens before modifying the security parameters, the downloaded excel reports might be faulty.
====

. To enable or disable the custom settings for your ONTAP clusters, select the required general setting under *Cluster*. For information on the options for customizing cluster compliance, see link:../health-checker/reference_cluster_compliance_categories.html[Cluster compliance categories]
. To enable or disable the custom settings for your storage VMs, select  the required general setting under *Storage VM*. For information on the options for customizing storage VM compliance, see link:../health-checker/reference_svm_compliance_categories.html[Storage VM compliance categories].
. You can also specify whether HTTPS transport is to be used for sending AutoSupport messages from ONTAP.
. If you enable the authentication settings, alerts are raised from Unified Manager for the default ONTAP administrator user.

---
