---
permalink: config/concept_security_dashboard.html
sidebar: sidebar
keywords: security dashboard
summary: "You can enable or disable the Security panel on the Active IQ Unified Manager dashboard. When enabled, you can also customize the settings for compliance monitoring and the relevant security events and management actions."
---
= Security Dashboard
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable the Security panel on the Active IQ Unified Manager dashboard. When enabled, you can also customize the settings for compliance monitoring and the relevant security events and management actions.

[NOTE]
====
Only users with administrator role can edit these settings.
====

The security criteria for your ONTAP clusters, storage VMs, and volumes are evaluated against the recommendations defined in the NetApp Security Hardening Guide for ONTAP 9. The security panel on the dashboard displays the security compliance status of your clusters, storage VMs, and volumes. Enabling this feature also generate security events for any cluster or storage VM that has security violations.

== Customizing settings

On enabling this feature, you can customize the settings for compliance monitoring as applicable to your ONTAP environment. These settings trigger the relevant security events and management actions. Follow these steps:

. Click *Customize*. The Customize Security Dashboard Settings pop-up appears.

[NOTE]
====
The security parameters that you enable or disable will directly affect the default view of the security grid.
====
. To enable or disable the custom settings for your ONTAP clusters, expand the *General Settings* selection for Clusters. For information on the options for customizing cluster compliance, see _Cluster compliance categories_ in the _Workflow Guide for Managing Cluster Health_.
. To enable or disable the custom settings for your storage VMs, expand the *General Settings* selection for Storage VMs. For information on the options for customizing storage VM compliance, see _Storage VM compliance categories_ in the _Workflow Guide for Managing Cluster Health_.
. You can also specify whether HTTPS transport is to be used for sending AutoSupport messages from ONTAP.
. If you enable the authentication settings, alerts are raised from Unified Manager for the default ONTAP administrator user.
