---
permalink: config/concept_authentication_with_active_directory_or_openldap.html
sidebar: sidebar
keywords: authentication, active directory, openldap
summary: "You can enable remote authentication on the management server and configure the management server to communicate with your authentication servers so that users within the authentication servers can access Unified Manager."
---
= Authentication with Active Directory or OpenLDAP
:icons: font
:imagesdir: ../media/

[.lead]
You can enable remote authentication on the management server and configure the management server to communicate with your authentication servers so that users within the authentication servers can access Unified Manager.

You can use one of the following predefined authentication services or specify your own authentication service:

* Microsoft Active Directory
+
[NOTE]
====
You cannot use Microsoft Lightweight Directory Services.
====

* OpenLDAP

You can select the required authentication service and add the appropriate authentication servers to enable the remote users in the authentication server to access Unified Manager. The credentials for remote users or groups are maintained by the authentication server. The management server uses the Lightweight Directory Access Protocol (LDAP) to authenticate remote users within the configured authentication server.

For local users who are created in Unified Manager, the management server maintains its own database of user names and passwords. The management server performs the authentication and does not use Active Directory or OpenLDAP for authentication.
