---
permalink: config/reference_support_and_diagnostics_menu.html
sidebar: sidebar
keywords: support and diagnostics, menu
summary: "The Support and Diagnostics menu enables you to generate a support bundle that you can send to technical support for troubleshooting assistance."
---
= Support and Diagnostics menu
:icons: font
:imagesdir: ../media/

[.lead]
The Support and Diagnostics menu enables you to generate a support bundle that you can send to technical support for troubleshooting assistance.

The following menu options are available:

* *Generate Light Support Bundle*
+
Enables you to produce a lightweight support bundle that contains just 30 days of logs and configuration database records -- it excludes performance data, acquisition recording files, and server heap dump.

* *Generate Support Bundle*
+
Enables you to create a full support bundle (7-Zip file) containing diagnostic information in the diagnostic user's home directory. If your system is connected to the internet you can also upload the support bundle to NetApp.
+
The file includes information generated by an AutoSupport message, the contents of the Unified Manager database, detailed data about the Unified Manager server internals, and verbose-level logs not normally included in AutoSupport messages or in the lightweight support bundle.
