---
permalink: config/task_view_https_security_certificate_ocf.html
sidebar: sidebar
keywords: view, https, security, certificate
summary: "You can compare the HTTPS certificate details to the retrieved certificate in your browser to ensure that your browser’s encrypted connection to Unified Manager is not being intercepted."
---
= Viewing the HTTPS security certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can compare the HTTPS certificate details to the retrieved certificate in your browser to ensure that your browser's encrypted connection to Unified Manager is not being intercepted.

*What you'll need*

You must have the Operator, Application Administrator, or Storage Administrator role.

Viewing the certificate enables you to verify the content of a regenerated certificate, or to view Subject Alt Names (SAN) from which you can access Unified Manager.

.Step

. In the left navigation pane, click *General* > *HTTPS Certificate*.
+
The HTTPS certificate is displayed at the top of the page

If you need to view more detailed information about the security certificate than what is displayed on the HTTPS Certificate page, you can view the connection certificate in your browser.
