---
permalink: config/task_set_up_authentication_services.html
sidebar: sidebar
keywords: set up, authentication, services
summary: "Authentication services enable the authentication of remote users or remote groups in an authentication server before providing them access to Unified Manager. You can authenticate users by using predefined authentication services (such as Active Directory or OpenLDAP), or by configuring your own authentication mechanism."
---
= Setting up authentication services
:icons: font
:imagesdir: ../media/

[.lead]
Authentication services enable the authentication of remote users or remote groups in an authentication server before providing them access to Unified Manager. You can authenticate users by using predefined authentication services (such as Active Directory or OpenLDAP), or by configuring your own authentication mechanism.

*What you'll need*

* You must have enabled remote authentication.
* You must have the Application Administrator role.

.Steps

. In the left navigation pane, click *General* > *Remote Authentication*.
. Select one of the following authentication services:
+
[cols="2*",options="header"]
|===
| If you select...| Then do this...
a|
Active Directory
a|

 .. Enter the administrator name and password.
 .. Specify the base distinguished name of the authentication server.
+
For example, if the domain name of the authentication server is +ou@domain.com+, then the base distinguished name is *cn=ou,dc=domain,dc=com*.

a|
OpenLDAP
a|

 .. Enter the bind distinguished name and bind password.
 .. Specify the base distinguished name of the authentication server.
+
For example, if the domain name of the authentication server is +ou@domain.com+, then the base distinguished name is *cn=ou,dc=domain,dc=com*.

a|
Others
a|

 .. Enter the bind distinguished name and bind password.
 .. Specify the base distinguished name of the authentication server.
+
For example, if the domain name of the authentication server is +ou@domain.com+, then the base distinguished name is *cn=ou,dc=domain,dc=com*.

 .. Specify the LDAP protocol version that is supported by the authentication server.
 .. Enter the user name, group membership, user group, and member attributes.

+
|===
+
[NOTE]
====
If you want to modify the authentication service, you must delete any existing authentication servers, and then add new authentication servers.
====

. Click *Save*.
