---
permalink: config/task_change_local_user_password.html
sidebar: sidebar
keywords: change, local, user, password
summary: "You can change your local user login password to prevent potential security risks."
---
= Changing the local user password
:icons: font
:imagesdir: ../media/

[.lead]
You can change your local user login password to prevent potential security risks.

*What you'll need*

You must be logged in as a local user.

The passwords for the maintenance user and for remote users cannot be changed using these steps. To change a remote user password, contact your password administrator. To change the maintenance user password, see link:task_use_maintenance_console.html[Using the maintenance console].

.Steps

. Log in to Unified Manager.
. From the top menu bar, click the user icon and then click *Change Password*.
+
The *Change Password* option is not displayed if you are a remote user.

. In the Change Password dialog box, enter the current password and the new password.
. Click *Save*.

If Unified Manager is configured in a high-availability configuration, you must change the password on the second node of the setup. Both instances must have same password.
