---
permalink: config/task_regenerate_client_certificate.html
sidebar: sidebar
keywords: client certificate, regenerate, validity, maintenance console
summary: ""
---
= Regenerate the client certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can regenerate the client certificates for Unified Manager using the maintainance console. This generates the certificate in the cluster with an extended validity of 5 years.

.Before you begin
You must have the required privileges to perform this operation.

.Steps

. Access the maintenance console.
. Select *Regenerate Client Certificate* and press *Enter*.
. If the system prompts for authentication, enter the required credentials.
. Select *Confirm Regeneration* and press *Enter*.
. After the certificate is regenerated, restart the Unified Manager service to apply the changes.
. You can verify the updated certificate by logging into ONTAP and checking the client certificate status. and updated validity. How do I check the client cert status in ONTAP ? 

// 2025-7-10, OTHERDOC 152