---
permalink: install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html
sidebar: sidebar
keywords: linux software, installation requirements, system, authorization,  requirements
summary: "The Linux system on which you install Unified Manager requires specific versions of the operating system and supporting software."
---
= Linux software and installation requirements
:icons: font
:imagesdir: ../media/

[.lead]
The Linux system on which you install Unified Manager requires specific versions of the operating system and supporting software.

== Operating system software

The Linux system must have the following versions of the operating system and supporting software installed:

* Red Hat Enterprise Linux versions 7.x and from 8.0 to 8.7, based on x86_64 architecture.
* CentOS version 7.x based on x86_64 architecture. CentOS Stream is not supported.

See the Interoperability Matrix for the complete and most current list of supported Red Hat Enterprise Linux and CentOS versions.

http://mysupport.netapp.com/matrix[mysupport.netapp.com/matrix]

== Third-party software

Unified Manager is deployed on a WildFly web server. WildFly 26.1.3 is bundled and configured with Unified Manager.

The following third-party packages are required, but not included with Unified Manager. These packages are automatically installed by the `yum` installer during installation, provided you have configured the repositories as mentioned in the following sections.

* MySQL Community Edition version 8.0.32 (from the MySQL repository).
* OpenJDK version 11.0.18 (from the Red Hat Extra Enterprise Linux Server repository)
* Python 3.6.x
* p7zip version 16.02 or later (from the Red Hat Extra Packages for Enterprise Linux repository)

[NOTE]
====
You must shut down a running instance of Unified Manager before upgrading any third-party software. After the third-party software installation is complete, you can restart Unified Manager.
====

== User authorization requirements

Installation of Unified Manager on a Linux system can be performed by the root user or by non-root users by using the `sudo` command.

== Installation requirements

The best practices for installing Red Hat Enterprise Linux or CentOS and the associated repositories on your system are listed below. Systems installed or configured differently, or deployed off premise (in the cloud), might require additional steps, and Unified Manager might not run properly in such deployments.

* You must install Red Hat Enterprise Linux or CentOS according to Red Hat best practices, and you should select the following default options, which requires selecting the "`Server with GUI`" base environment.
* While installing Unified Manager on Red Hat Enterprise Linux or CentOS, the system must have access to the appropriate repository so that the installation program can access and install all the required software dependencies.
* For the `yum` installer to find dependent software in the Red Hat Enterprise Linux repositories, you must have registered the system during the Red Hat Enterprise Linux installation or afterwards by using a valid Red Hat subscription.
+
See the Red Hat documentation for information about the Red Hat Subscription Manager.

* You must enable the Extra Packages for Enterprise Linux (EPEL) repository to successfully install the required third-party utilities on your system.
+
If the EPEL repository is not configured on your system, you must manually download and configure the repository.
+
See link:task_manually_configure_epel_repository.html[Manually configuring the EPEL repository].

* If the correct version of MySQL is not installed, you must enable the MySQL repository to successfully install MySQL software on your system.
+
If the MySQL repository is not configured on your system, you must manually download and configure the repository.
+
See link:task_manually_configure_mysql_repository.html[Manually configuring the MySQL repository].

If your system does not have internet access, and the repositories are not mirrored from an internet-connected system to the unconnected system, you should follow the installation instructions to determine the external software dependencies of your system. Then you can download the required software to the internet-connected system, and copy the `.rpm` files to the system on which you plan to install Unified Manager. To download the artifacts and packages, you must use the `yum install` command. You must ensure that the two systems are running the same operating system version and that the subscription license is for the appropriate Red Hat Enterprise Linux or CentOS version.

[NOTE]
====
You must not install the required third-party software from repositories other than the repositories that are listed here. Software installed from the Red Hat repositories is designed explicitly for Red Hat Enterprise Linux, and conforms to Red Hat best practices (directory layouts, permissions, and so on). Software from other locations might not follow these guidelines, which might cause the Unified Manager installation to fail, or might cause issues with future upgrades.
====

== Port 443 requirement

Generic images of Red Hat Enterprise Linux and CentOS might block external access to port 443. Due to this restriction, you might be unable to connect to the Administrator web UI after installing Unified Manager. Running the following command allows access to port 443 for all external users and applications on a generic Red Hat Enterprise Linux or CentOS system.

`# firewall-cmd --zone=public --add-port=443/tcp --permanent; firewall-cmd --reload`

You must install Red Hat Enterprise Linux and CentOS with the "`Server with GUI`" base environment. It provides the commands used by Unified Manager installation instructions. Other base environments might require you to install additional commands to validate or complete the installation. If the `firewall-cmd` is not available on your system, you must install it by running the following command:

`# sudo yum install firewalld`

Contact your IT department before running the commands to see if your security policies require a different procedure.

[NOTE]
====
THP (Transparent Huge Pages) should be disabled on CentOS and Red Hat systems. When enabled, in some cases it can cause Unified Manager to be shut down when certain processes consume too much memory and are terminated.
====
