---
permalink: install-linux/task_manually_configure_mysql_repository.html
sidebar: sidebar
keywords: manually configure mysql repository, mysql key, keys update
summary: "If the system on which you are installing Unified Manager does not have access to the MySQL Community Edition repository, then you must manually download and configure the repository for a successful installation."
---
= Manually configure the MySQL repository
:icons: font
:imagesdir: ../media/

[.lead]
If the system on which you are installing Unified Manager does not have access to the MySQL Community Edition repository, then you must manually download and configure the repository for a successful installation.

The MySQL repository provides access to the required MySQL software that must be installed on your system.

[NOTE]
====
This task might fail if the system does not have the internet connectivity. Refer to the MySQL documentation if the system on which you are installing Unified Manager does not have the internet access.
====
.Steps

. Download the appropriate MySQL repository for your installation. For version 8, download it from:
+
`wget http://repo.mysql.com/yum/mysql-8.4-community/el/8/x86_64/mysql84-community-release-el8-1.noarch.rpm` 
+
For version 9, download it from:
+
`wget http://repo.mysql.com/yum/mysql-8.4-community/el/9/x86_64/mysql84-community-release-el9-1.noarch.rpm`

. Configure the MySQL repository:
+
`yum install mysql84-community-release-.noarch.rpm`

For Red Hat Enterprise Linux 8 system, if you have internal repositories with java-11-openjdk, p7zip, and other software packages provided by the AppStream repository, you must disable your AppStream repository and install MySQL Community Server. Run the following command:

----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----


If you receive an error on missing key or key mismatch, and your installation fails, try these steps:

* On a connected system, import the updated MySQL key by running the following command:

----
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-<xxxx>

for example:

rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023 
----
** On a system that does not have internet connectivity, update your MySQL repo file and disable `gpgcheck` by marking `gpgcheck=0`.

// 15-November-2024 OTHERDOC-81
// 9-June-2025 OTHERDOC- 127

