---
permalink: install-linux/task_download_unified_manager.html
sidebar: sidebar
keywords: download, Unified Manager
summary: "You must download the Unified Manager `.zip` file from the NetApp Support Site to install Unified Manager."
---
= Downloading Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
You must download the Unified Manager `.zip` file from the NetApp Support Site to install Unified Manager.

*What you'll need*

You must have login credentials for the NetApp Support Site.

You download the same Unified Manager installation package for both Red Hat Enterprise Linux and CentOS systems.

.Steps

. Log in to the NetApp Support Site, and navigate to the Download page for Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab[NetApp Support Site]
. Select the required version of Unified Manager and accept the end-users license agreement (EULA).
. Download the Unified Manager installer file for Linux, and save the `.zip` file to a directory on the target system.
+
[NOTE]
====
** Ensure that you download the correct version of the installer file for your Red Hat Enterprise Linux system. Based on whether you have Red Hat Enterprise Linux 7 or 8 installed, ensure that you download the appropriate version of the Unified Manager `.zip` file.
** NetApp recommends that you download the code signing certificate (`.pem`) and digital signature (`.sig`) along with the `.zip` file. 
====
. Verify the checksum for integrity of the  downloaded software.
. If you have downloaded the code signing certificate and digital signature, you can verify the integrity of the installer file. You can use the following commands to verify the integrity of the installer file:
** This command creates a file with the public key from the code signing certificate:
+
----
openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>
----
*** Where *AIQUM-RHEL-CLIENT-INTER-ROOT.pem* is the file that contains the code signing certificate.

** This command verifies the signature on the installer file:
+
----
openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip
----
+
The message similar to `Verified Ok` confirms that the installer file is safe to use.
