---
permalink: install-linux/task_upgrade_unified_manager.html
sidebar: sidebar
keywords: upgrade, unified manager
summary: "You can upgrade Unified Manager by downloading and running the installation file on the Red Hat platform."
---
= Upgrading Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade from Unified Manager 9.8 or 9.9 to 9.10 by downloading and running the installation file on the Red Hat platform.

*What you'll need*

* The system on which you are upgrading Unified Manager must meet the system and software requirements.
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html[Hardware system requirements]
+
link:reference_red_hat_and_centos_software_and_installation_requirements.html[Red Hat and CentOS software and installation requirements]

* You must install, or upgrade to the correct version of OpenJDK prior to upgrading Unified Manager.
+
link:task_upgrade_openjdk_on_linux_ocum.html[Upgrading JRE on Linux]
+

* You must have a subscription to the Red Hat Enterprise Linux Subscription Manager.
* To avoid data loss, you must have created a backup of the Unified Manager database in case there is an issue during the upgrade. It is also recommended that you move the backup file from the `/opt/netapp/data` directory to an external location.
* During upgrade, you may be prompted to confirm whether you want to keep the previous, default settings for retaining performance data for 13 months or to change it to 6 months. On confirming, the historical performance data after 6 months is purged.
* You should have completed any running operations, because Unified Manager is unavailable during the upgrade process.
* *MySQL Requirement*:
MySQL Community Edition is automatically upgraded during Unified Manager upgrade. If the installed version of MySQL on your system is earlier than 8.0.27, the Unified Manager upgrade process automatically upgrades MySQL to 8.0.27.
+
However, you may want to upgrade MySQL to the latest minor version on your system. Before an upgrade to the next minor version, ensure that the base version of MySQL on your system is 8.0.27.
+
If your site does not have a repository configured with MySQL 8.0.27, you might not be able to upgrade Unified Manager. To configure the repository before upgrade, follow these steps:

. Download the MySQL RPM packages with the minimum version required (in this case 8.0.27), and save them in the same directory where `netapp-um<version>.x86_64.rpm` is stored.
. Run this command to install the new version:
`yum install *.rpm`
. Start the Unified Manager server. Run these commands:
.. `systemctl start ocie`
.. `systemctl start ocieau`

.Steps

. Log in to the target Red Hat Enterprise Linux or CentOS server.
. Download the Unified Manager bundle to the server.
+
link:task_download_unified_manager.html[Downloading Unified Manager for Red Hat or CentOS]

. Navigate to the target directory and expand the Unified Manager bundle:
+
`unzip ActiveIQUnifiedManager-<version>.zip`
+
The required RPM modules for Unified Manager are unzipped to the target directory.

. Verify that the following module is available in the directory:
+
`ls *.rpm`
+
`netapp-um<version>.x86_64.rpm`
+
. *Optional:* For systems that are not connected to the Internet or that are not using the Red Hat Enterprise Linux repositories, perform the following steps to determine whether you are missing any required packages and download those packages:
 .. View the list of available and unavailable packages:
+
`yum install netapp-um<version>.x86_64.rpm --assumeno`
+
The items in the "`Installing:`" section are the packages that are available in the current directory, and the items in the "`Installing for dependencies:`" section are the packages that are missing on your system.

 .. On a different system that has Internet access, run the following command to download the missing packages.
+
`yum install package_name --downloadonly --downloaddir=.`
+
The packages are downloaded in the directory specified as `--downloaddir=`.
+
Because the plug-in "`yum-plugin-downloadonly`" is not always enabled on Red Hat Enterprise Linux systems, you might need to enable the functionality to download a package without installing it:
+
`yum install yum-plugin-downloadonly`

 .. Create a new directory in the installation system and copy the downloaded packages from the Internet-connected system.
 .. Change directories to the new directory on the installation system and run the following command for installing MySQL Community Edition, along with its dependencies.
+
`yum install *.rpm`
. Run the pre-installation script to ensure that there are no system configuration settings or any installed software that might conflict with the upgrade:
+
`sudo ./pre_install_check.sh`
+
The pre-installation script checks that the system has a valid Red Hat subscription, and that it has access to the required software repositories. If the script identifies any issues, you must fix the issues before upgrading Unified Manager.

. Upgrade Unified Manager using the following script:
+
`upgrade.sh`
+
This script automatically executes the RPM modules, upgrading the necessary supporting software and the Unified Manager modules that run on them. Additionally, the upgrade script checks whether there are any system configuration settings or any installed software that might conflict with the upgrade. If the script identifies any issues, you must fix the issues before upgrading Unified Manager.

. After the upgrade is complete, scroll back through the messages until you see the message displaying an IP address or URL for the Unified Manager web UI, the maintenance user name (umadmin), and the default password.
+
The message is similar to the following:
+
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----

Enter the specified IP address or URL into a supported web browser to start the Unified Manager web UI, and then log in by using the same maintenance user name (umadmin) and password that you set earlier.
