---
permalink: install-linux/task_remove_unified_manager.html
sidebar: sidebar
keywords: remove, unified manager
summary: "You can stop and uninstall Unified Manager from the Red Hat Enterprise Linux or CentOS host with a single command."
---
= Removing Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can stop and uninstall Unified Manager from the Red Hat Enterprise Linux or CentOS host with a single command.

*What you'll need*

* You must have root user access to the server from which you want to remove Unified Manager.
* Security-Enhanced Linux (SELinux) must be disabled on the Linux system. Change the SELinux runtime mode to "`Permissive`" by using the `setenforce 0` command.
* All clusters (data sources) must be removed from the Unified Manager server before removing the software.
* You should manually delete the firewall rules that are created to allow or block MySQL port 3306. The firewall rules are not deleted automatically.

.Steps

. Log in as root user to the server on which you want to remove Unified Manager.
. Stop and remove Unified Manager from the server:
+
`rpm -e netapp-um`
+
This step removes all the associated NetApp RPM packages. It does not remove the prerequisite software modules, such as Java, MySQL, and p7zip.

. *Optional:* If appropriate, remove the supporting software modules, such as Java, MySQL, and p7zip:
+
`rpm -e p7zip mysql-community-client mysql-community-server mysql-community-common mysql-community-libs java-x.y`

After this operation is complete, the software is removed. All the data from the `/opt/netapp/data` directory is moved to the `/opt/netapp/data/BACKUP` folder after uninstallation. Uninstalling Unified Manager removes the Java and MySQL packages also, unless the packages are required and used by any other application on the system. However, MySQL data is not deleted.
