---
permalink: install-linux/task_change_jboss_password.html
sidebar: sidebar
keywords: change, jboss password
summary: "You can reset the instance-specific JBoss password that is set during installation. You can reset the password optionally, in case your site requires this security capability to override the Unified Manager installation setting. This operation also changes the password JBoss uses to access MySQL."
---
= Changing the JBoss password
:icons: font
:imagesdir: ../media/

[.lead]
You can reset the instance-specific JBoss password that is set during installation. You can reset the password optionally, in case your site requires this security capability to override the Unified Manager installation setting. This operation also changes the password JBoss uses to access MySQL.

* You must have root user access to the Red Hat Enterprise Linux or CentOS system on which Unified Manager is installed.
* You must be able to access the NetApp-provided `password.sh` script in the directory `/opt/netapp/essentials/bin`.

.Steps

. Log in as root user on the system.
. Stop the Unified Manager services by entering the following commands in the order shown:
+
`systemctl stop ocieau`
+
`systemctl stop ocie`
+
Do not stop the associated MySQL software.

. Enter the following command to begin the password change process:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. When prompted, enter the new JBoss password, and then enter it a second time for confirmation.
+
Note that the password should be between 8 and 16 characters, and must contain at least a digit, an upper case and lower case characters, and at least one of these special characters:
+
`+!@%^*-_+=[]:<>.?/~+`

. When the script completes, start the Unified Manager services by entering the following commands in the order shown:
+
`systemctl start ocie`
+
`systemctl start ocieau`
. After all of the services are started, you can log in to the Unified Manager UI.
