---
permalink: events/concept_what_event_management_system_events_are.html
sidebar: sidebar
keywords: event management, system,
summary: "The Event Management System (EMS) collects event data from different parts of the ONTAP kernel and provides event forwarding mechanisms. These ONTAP events can be reported as EMS events in Unified Manager. Centralized monitoring and management eases configuration of critical EMS events and alert notifications based on these EMS events."
---
= What Event Management System events are
:icons: font
:imagesdir: ../media/

[.lead]
The Event Management System (EMS) collects event data from different parts of the ONTAP kernel and provides event forwarding mechanisms. These ONTAP events can be reported as EMS events in Unified Manager. Centralized monitoring and management eases configuration of critical EMS events and alert notifications based on these EMS events.

The Unified Manager address is added as a notification destination to the cluster when you add the cluster to Unified Manager. An EMS event is reported as soon as the event occurs in the cluster.

There are two methods for receiving EMS events in Unified Manager:

* A certain number of important EMS events are reported automatically.
* You can subscribe to receive individual EMS events.

The EMS events that are generated by Unified Manager are reported differently depending on the method in which the event was generated:
[options="header"]
|===
| Functionality| Automatic EMS messages| Subscribed EMS messages
a|
Available EMS events
a|
Subset of EMS events
a|
All EMS events
a|
EMS message name when triggered
a|
Unified Manager event name (converted from EMS event name)
a|
Non-specific in the format "Error EMS received". The detailed message provides the dot-notation format of the actual EMS event
a|
Messages received
a|
As soon as the cluster has been discovered
a|
After adding each required EMS event to Unified Manager, and after the next 15 minute polling cycle
a|
Event life cycle
a|
Same as other Unified Manager events: New, Acknowledged, Resolved, and Obsolete states
a|
The EMS event is made obsolete after the cluster is refreshed, after 15 minutes, from when the event was created
a|
Captures events during Unified Manager downtime
a|
Yes, when the system starts up it communicates with each cluster to acquire missing events
a|
No
a|
Event details
a|
Suggested corrective actions are imported directly from ONTAP to provide consistent resolutions
a|
Corrective actions not available in Event Details page
|===

[NOTE]
====
Some of the new automatic EMS events are Informational events that indicate that a previous event has been resolved. For example, the "FlexGroup Constituents Space Status All OK" Informational event indicates that the "FlexGroup Constituents Have Space Issues" Error event has been resolved. Informational events cannot be managed using the same event life cycle as other event severity types, however, the event is obsoleted automatically if the same volume receives another "`Space Issues`" Error event.
====
