---
permalink: events/concept_what_active_iq_platform_events_are.html
sidebar: sidebar
keywords: Active IQ
summary: 'Unified Manager can display events that have been discovered by the Active IQ platform. These events are created by running a set of rules against AutoSupport messages generated from all storage systems being monitored by Unified Manager.'
---
= What Active IQ platform events are
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager can display events that have been discovered by the Active IQ platform. These events are created by running a set of rules against AutoSupport messages generated from all storage systems being monitored by Unified Manager.

Unified Manager checks for a new rules file automatically and only downloads a new file when there are newer rules. In sites with no external network access, you need to upload the rules manually from *Storage Management* > *Event Setup* > *Upload Rules*.

These Active IQ events do not overlap with existing Unified Manager events, and they identify incidents or risks concerning system configuration, cabling, best practice, and availability issues.

NetApp Active IQ is a cloud based service that provides predictive analytics and proactive support to optimize storage system operations across the NetApp hybrid cloud. See https://www.netapp.com/us/products/data-infrastructure-management/active-iq.aspx[NetApp Active IQ] for more information.
