---
permalink: events/reference_enclosures_events.html
sidebar: sidebar
keywords: enclosures, events, impact area, availability, configuration
summary: "Enclosures events provide you with information about the status of disk shelf enclosures in your data center so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity."
---
= Enclosures events
:icons: font
:imagesdir: ../media/

[.lead]
Enclosures events provide you with information about the status of disk shelf enclosures in your data center so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.

== Impact area: availability
[options="header"]
|===
| Event name (Trap name)| Impact level| Source type| Severity
a|
Disk Shelf Fans Failed(ocumEvtShelfFanFailed)

a|
Incident
a|
Storage shelf
a|
Critical
a|
Disk Shelf Power Supplies Failed(ocumEvtShelfPowerSupplyFailed)

a|
Incident
a|
Storage shelf
a|
Critical
a|
Disk Shelf Multipath Not Configured(ocumDiskShelfConnectivityNotInMultiPath)

This event does not apply to:

* Clusters that are in a MetroCluster configuration
* The following platforms: FAS2554, FAS2552, FAS2520, and FAS2240

a|
Risk
a|
Node
a|
Warning
a|
Disk Shelf Path Failure(ocumDiskShelfConnectivityPathFailure)

a|
Risk
a|
Storage Shelf
a|
Warning
|===

== Impact area: configuration
[options="header"]
|===
| Event name (Trap name)| Impact level| Source type| Severity
a|
Disk Shelf Discovered(Not applicable)

a|
Event
a|
Node
a|
Information
a|
Disk Shelves Removed(Not applicable)

a|
Event
a|
Node
a|
Information
|===
