---
permalink: events/reference_management_station_events.html
sidebar: sidebar
keywords: management, station, events, impact area, configuration, performance
summary: "Management station events provide you with information about the status of server on which Unified Manager is installed so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity."
---
= Management station events
:icons: font
:imagesdir: ../media/

[.lead]
Management station events provide you with information about the status of server on which Unified Manager is installed so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.

== Impact area: configuration
[options="header"]
|===
| Event name (Trap name)| Impact level| Source type| Severity
a|
Management Server Disk Space Nearly Full(ocumEvtUnifiedManagerDiskSpaceNearlyFull)

a|
Risk
a|
Management station
a|
Warning
a|
Management Server Disk Space Full(ocumEvtUnifiedManagerDiskSpaceFull)

a|
Incident
a|
Management station
a|
Critical
a|
Management Server Low On Memory(ocumEvtUnifiedManagerMemoryLow)

a|
Risk
a|
Management station
a|
Warning
a|
Management Server Almost Out Of Memory(ocumEvtUnifiedManagerMemoryAlmostOut)

a|
Incident
a|
Management station
a|
Critical
a|
MySQL Log File Size Increased; Restart Required(ocumEvtMysqlLogFileSizeWarning)

a|
Incident
a|
Management station
a|
Warning
|===

== Impact area: performance
[options="header"]
|===
| Event name (Trap name)| Impact level| Source type| Severity
a|
Performance Data Analysis Is Impacted(ocumEvtUnifiedManagerDataMissingAnalyze)

a|
Risk
a|
Management station
a|
Warning
a|
Performance Data Collection Is Impacted(ocumEvtUnifiedManagerDataMissingCollection)

a|
Incident
a|
Management station
a|
Critical
|===

[NOTE]
====
These last two performance events were available for Unified Manager 7.2 only. If either of these events exist in the New state, and then you upgrade to a newer version of Unified Manager software, the events will not be purged automatically. You will need to move the events to the Resolved state manually.
====
