---
permalink: events/reference_snapmirror_and_vault_relationship_events.html
sidebar: sidebar
keywords: asynchronous, mirror, vault, relationship, events, impact area, protection
summary: "Asynchronous Mirror and Vault relationship events provide you with information about the status of your Asynchronous SnapMirror and Vault relationships so that you can monitor for potential problems. Asynchronous Mirror and Vault relationship events are supported for both volume and Storage VM protection relationships. But only Vault relationships are not supported for Storage VM disaster recovery. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity."
---
= Asynchronous Mirror and Vault relationship events
:icons: font
:imagesdir: ../media/

[.lead]
Asynchronous Mirror and Vault relationship events provide you with information about the status of your Asynchronous SnapMirror and Vault relationships so that you can monitor for potential problems. Asynchronous Mirror and Vault relationship events are supported for both volume and Storage VM protection relationships. But only Vault relationships are not supported for Storage VM disaster recovery. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.

== Impact area: protection

[NOTE]
====

The SnapMirror and Vault relationships events are also generated for Storage VMs that are protected by Storage VM disaster recovery but not for any constituent object relationships.

====
[options="header"]
|===
| Event name (Trap name)| Impact level| Source type| Severity
a|
Asynchronous Mirror and Vault Unhealthy(ocumEvtMirrorVaultRelationshipUnhealthy)

a|
Risk
a|
SnapMirror relationship
a|
Warning
a|
Asynchronous Mirror and Vault Broken-off(ocumEvtMirrorVaultRelationshipStateBrokenoff)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Initialize Failed(ocumEvtMirrorVaultRelationshipInitializeFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Update Failed(ocumEvtMirrorVaultRelationshipUpdateFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Lag Error(ocumEvtMirrorVaultRelationshipLagError)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Lag Warning(ocumEvtMirrorVaultRelationshipLagWarning)

a|
Risk
a|
SnapMirror relationship
a|
Warning
a|
Asynchronous Mirror and Vault Resync Failed(ocumEvtMirrorVaultRelationshipResyncFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
|===

[NOTE]
====
"SnapMirror update failure" event is raised by Active IQ portal (Config Advisor).
====
