---
permalink: events/reference_snapvault_relationship_events.html
sidebar: sidebar
keywords: snapvault, relationship, events, impact area, protection
summary: "SnapVault relationship events provide you with information about the status of your SnapVault relationships so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity."
---
= SnapVault relationship events
:icons: font
:imagesdir: ../media/

[.lead]
SnapVault relationship events provide you with information about the status of your SnapVault relationships so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.

== Impact area: protection
[options="header"]
|===
| Event name (Trap name)| Impact level| Source type| Severity
a|
Asynchronous Vault Unhealthy(ocumEvtSnapVaultRelationshipUnhealthy)

a|
Risk
a|
SnapMirror relationship
a|
Warning
a|
Asynchronous Vault Broken-off(ocumEvtSnapVaultRelationshipStateBrokenoff)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Vault Initialize Failed(ocumEvtSnapVaultRelationshipInitializeFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Vault Update Failed(ocumEvtSnapVaultRelationshipUpdateFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Vault Lag Error(ocumEvtSnapVaultRelationshipLagError)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Vault Lag Warning(ocumEvtSnapVaultRelationshipLagWarning)

a|
Risk
a|
SnapMirror relationship
a|
Warning
a|
Asynchronous Vault Resync Failed(ocumEvtSnapvaultRelationshipResyncFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
|===
