---
permalink: events/reference_notifications_page.html
sidebar: sidebar
keywords: notifications page, email, smtp, server, snmp
summary: "You can configure the Unified Manager server to send notifications when an event is generated or when it is assigned to a user. You can also configure the notification mechanisms. For example, notifications can be sent as emails or SNMP traps."
---
= Notifications page
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the Unified Manager server to send notifications when an event is generated or when it is assigned to a user. You can also configure the notification mechanisms. For example, notifications can be sent as emails or SNMP traps.

You must have the Application Administrator or Storage Administrator role.

== Email

This area enables you to configure the following email settings for alert notification:

* *From Address*
+
Specifies the email address from which the alert notification is sent. This value is also used as the from address for a report when shared. If the From Address is pre-filled with the address "ActiveIQUnifiedManager@localhost.com", you should change it to a real, working email address to make sure that all email notifications are delivered successfully.

== SMTP Server

This area enables you to configure the following SMTP server settings:

* *Host Name or IP Address*
+
Specifies the host name of your SMTP host server, which is used to send the alert notification to the specified recipients.

* *User Name*
+
Specifies the SMTP user name. SMTP user name is required only when the SMTPAUTH is enabled in the SMTP server.

* *Password*
+
Specifies the SMTP password. SMTP user name is required only when the SMTPAUTH is enabled in the SMTP server.

* *Port*
+
Specifies the port that is used by the SMTP host server to send alert notification.
+
The default value is 25.

* *Use START/TLS*
+
Checking this box provides secure communication between the SMTP server and the management server by using the TLS/SSL protocols (also known as start_tls and StartTLS).

* *Use SSL*
+
Checking this box provides secure communication between the SMTP server and the management server by using the SSL protocol.

== SNMP

This area enables you to configure the following SNMP trap settings:

* *Version*
+
Specifies the SNMP version you want to use depending on the type of security you require. Options include Version 1, Version 3, Version 3 with Authentication, and Version 3 with Authentication and Encryption. The default value is Version 1.

* *Trap Destination Host*
+
Specifies the host name or IP address (IPv4 or IPv6) that receives the SNMP traps that are sent by the management server. To specify multiple trap destinations, separate each host with a comma.
+
[NOTE]
====
All other SNMP settings, such as "Version" and "Outbound Port", must be the same for all hosts in the list.
====

* *Outbound Trap Port*
+
Specifies the port through which the SNMP server receives the traps that are sent by the management server.
+
The default value is 162.

* *Community*
+
The community string to access the host.

* *Engine ID*
+
Specifies the unique identifier of the SNMP agent and is automatically generated by the management server. Engine ID is available with SNMP Version 3, SNMP Version 3 with Authentication, and SNMP Version 3 with Authentication and Encryption.

* *Username*
+
Specifies the SNMP user name. User name is available with SNMP Version 3, SNMP Version 3 with Authentication, and SNMP Version 3 with Authentication and Encryption.

* *Authentication Protocol*
+
Specifies the protocol used to authenticate a user. Protocol options include MD5 and SHA. MD5 is the default value. Authentication protocol is available with SNMP Version 3 with Authentication and SNMP Version 3 with Authentication and Encryption.

* *Authentication Password*
+
Specifies the password used when authenticating a user. Authentication password is available with SNMP Version 3 with Authentication and SNMP Version 3 with Authentication and Encryption.

* *Privacy Protocol*
+
Specifies the privacy protocol used to encrypt SNMP messages. Protocol options include AES 128 and DES. The default value is AES 128. Privacy protocol is available with SNMP Version 3 with Authentication and Encryption.

* *Privacy Password*
+
Specifies the password when using privacy protocol. Privacy password is available with SNMP Version 3 with Authentication and Encryption.

For more information about SNMP objects and traps, you can download the link:https://mysupport.netapp.com/site/tools/tool-eula/aiqum-mib[Active IQ Unified Manager MIB^] from the NetApp Support Site.

