---
permalink: events/task_upload_new_active_iq_rules_file.html
sidebar: sidebar
keywords: upload, new, active iq AIQ rules, rules file, CA secure rules, config advisor rules
summary: "Unified Manager checks for a new Active IQ rules file automatically and downloads a new file when there are newer rules. However, in sites with no external network access, you need to upload the rules file manually."
---
= Uploading a new Active IQ rules file
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager checks for a new Active IQ events (rules) file automatically and downloads a new file when there are newer rules.
However, in sites with no external network access, you need to upload the rules file manually.

[NOTE]
Active IQ rules are also referred to as Config Advisor (CA) secure rules.

When you are installing or upgrading Unified Manager to a specific release in a site without network connectivity, the bundled Active IQ rules are automatically available for upload. However, it is recommended that you download a new rules file approximately once a month from the support site to make sure that updated events are generated and your storage systems continue to perform optimally.

The bundled rules package includes the rules repository, data sources, and a NetApp KB article.
[NOTE]
On Windows systems, in an unconnected site, the KB article is not available by default in the bundled rules file. You can download and view the KB article from the support site.

The rules file is located at: https://mysupport.netapp.com/api/content-service/staticcontents/content/public/tools/unifiedmanager/ca/secure_rules.zip

*What you'll need*

* Active IQ event reporting must be enabled.
* You must download the rules file from the NetApp Support Site.

.Steps
. On a computer that has network access, navigate to the NetApp Support Site and download the current rules `.zip` file.
. Transfer the rules file to some media that you can bring into the secure area and then copy it onto a system in the secure area.
. In the left navigation pane, click *Storage Management* > *Event Setup*.
. In the *Event Setup* page, click the *Upload Rules* button.
. In the *Upload Rules* dialog box, navigate to and select the rules `.zip` file you downloaded and click *Upload*.
+
This process can take a few minutes.

The rules file is unzipped on the Unified Manager server. After your managed clusters generate an AutoSupport file after midnight, Unified Manager checks the clusters against the rules file and generates new risk and incident events if required.
