---
permalink: events/task_subscribe_to_ontap_ems_events.html
sidebar: sidebar
keywords: subscribe, ontap, ems events
summary: "You can subscribe to receive Event Management System (EMS) events that are generated by systems that are installed with ONTAP software. A subset of EMS events are reported to Unified Manager automatically, but additional EMS events are reported only if you have subscribed to these events."
---
= Subscribing to ONTAP EMS events
:icons: font
:imagesdir: ../media/

[.lead]
You can subscribe to receive Event Management System (EMS) events that are generated by systems that are installed with ONTAP software. A subset of EMS events are reported to Unified Manager automatically, but additional EMS events are reported only if you have subscribed to these events.

*What you'll need*

Do not subscribe to EMS events that are already added to Unified Manager automatically as this can cause confusion when receiving two events for the same issue.

You can subscribe to any number of EMS events. All the events to which you subscribe are validated, and only the validated events are applied to the clusters you are monitoring in Unified Manager. The _ONTAP 9 EMS Event Catalog_ provides detailed information for all of the EMS messages for the specified version of ONTAP 9 software. Locate the appropriate version of the _EMS Event Catalog_ from the ONTAP 9 Product Documentation page for a list of the applicable events.

https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[ONTAP 9 Product Library]

You can configure alerts for the ONTAP EMS events to which you subscribe, and you can create custom scripts to be executed for these events.

[NOTE]
====
If you do not receive the ONTAP EMS events to which you have subscribed, there might be an issue with the DNS configuration of the cluster which is preventing the cluster from reaching the Unified Manager server. To resolve this issue, the cluster administrator must correct the DNS configuration of the cluster, and then restart Unified Manager. Doing so will flush the pending EMS events to the Unified Manager server.
====

.Steps

. In the left navigation pane, click *Storage Management* > *Event Setup*.
. In the Event Setup page, click the *Subscribe to EMS events* button.
. In the Subscribe to EMS events dialog box, enter the name of the ONTAP EMS event to which you want to subscribe.
+
To view the names of the EMS events to which you can subscribe, from the ONTAP cluster shell, you can use the `event route show` command (prior to ONTAP 9) or the `event catalog show` command (ONTAP 9 or later).
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_and_receive_alerts_from_ONTAP_EMS_Event_Subscription_in_Active_IQ_Unified_Manager[How to configure and receive alerts from ONTAP EMS Event Subscription in Active IQ Unified Manager]

. Click *Add*.
+
The EMS event is added to the Subscribed EMS events list, but the Applicable to Cluster column displays the status as "`Unknown`" for the EMS event that you added.

. Click *Save and Close* to register the EMS event subscription with the cluster.
. Click *Subscribe to EMS events* again.
+
The status "`Yes`" appears in the Applicable to Cluster column for the EMS event that you added.
+
If the status is not "`Yes`", check the spelling of the ONTAP EMS event name. If the name is entered incorrectly, you must remove the incorrect event, and then add the event again.

When the ONTAP EMS event occurs, the event is displayed on the Events page. You can select the event to view details about the EMS event in the Event details page. You can also manage the disposition of the event or create alerts for the event.
