---
permalink: data-protection/task_restore_data_use_health_volume_details_page.html
sidebar: sidebar
keywords: restore, data, volume, health details page, console
summary: "You can restore overwritten or deleted files, directories, or an entire volume from a Snapshot copy by using the restore feature on the Volume / Health details page."
---
= Restore data using the Volume and Volume / Health details pages
:icons: font
:imagesdir: ../media/

[.lead]
You can restore overwritten or deleted files, directories, or an entire volume from a Snapshot copy by using the restore feature on the Volume and Volume / Health details pages.

.Before you begin

You must have the Application Administrator or Storage Administrator role.

[NOTE]
Note the following points:

* You can't restore a directory or a volume from a Snapshot copy in any of the following scenarios:
** The `Yes, preserve all snapshot copies` option is selected.
** You are using an LDAP account to monitor the cluster.
** You are logged in as a domain user.
** Your account is configured for SAML authentication.
** You are using the NDMP protocol.
+
For more details, see the Knowledge Base article https://kb.netapp.com/on-prem/ontap/DP/NDMP/NDMP-KBs/How_to_configure_NDMP_authentication_in_the_SVM-scope_previously_known_as_Vserver-scope_mode[How to configure NDMP authentication in 'SVM-scope' mode].
* You can't restore NTFS file streams.
* The restore option is not available when:
** The volume ID is unknown: for example, when you have an intercluster relationship and the destination cluster has not yet been discovered.
** The volume is configured for SnapMirror Synchronous replication.

.Steps

. From the left navigation pane, go to *Storage > Volumes*.
. Select the volume and click the *Restore* button. Alternately, click on the volume to go to *Volume / Health details > Actions > Restore*. The Restore dialog box is displayed. For information on this page, see link:../data-protection/reference_restore_dialog_box.html[Restore dialog box].
. Select the volume and Snapshot copy from which you want to restore data, if different from the default.
. Select the items you want to restore, for example, the source LUN.
+
You can restore the entire volume, or you can specify folders and files you want to restore.

. Select the location to which you want the selected items restored: either *Original Location* or *Alternate Existing Location*.
. If you select an alternate existing location, do one of the following:
 ** In the Restore Path text field, type the path of the location to which you want to restore the data and then click *Select Directory*.
 ** Click *Browse* to launch the Browse Directories dialog box and complete the following steps:
  ... Select the destination cluster, storage VM (SVM), and volume to which you want to restore.
  ... In the Name table, select a directory name that has to be restored.
  ... Click *Select Directory*.
. Click *Restore*.
+
The restore process begins. A job is created at the backend to complete the restore process. 
. If you want to view the job progress, from the left navigation pane, navigate to *Protection > Jobs* to view the status of the restore job from the list of jobs.

+
[NOTE]
====
If a restore operation fails between Cloud Volumes ONTAP HA clusters with an NDMP error, you may need to add an explicit AWS route in the destination cluster so that the destination can communicate with the source system's cluster management LIF. You perform this configuration step by using the NetApp Console.
====
// 2025-6-11, OTHERDOC-133
// 2025-9-1, BLUEXPDOC-806
// 2026-01-21, OTHERDOC 174