---
permalink: data-protection/task_view_storage_vms_based_on_protection_status.html
sidebar: sidebar
keywords: storage vm, view protection status
summary: "You can use the Storage VMs page of the Inventory to view all the storage VMs in Active IQ Unified Manager and filter the storage VMs based on their protection status."
---
= Viewing Storage VMs based on protection status
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Storage VMs page of the Inventory to view all the storage VMs in Active IQ Unified Manager and filter the storage VMs based on their protection status.

*What you'll need*

You must have the Application Administrator or Storage Administrator role.

A new column Protection Role is added to the storage VMs view that provides information on whether the storage VM is protected or unprotected.

[NOTE]
====
If a source cluster is not added to Active IQ Unified Manager, then all the information related to that cluster is unavailable in the grids.
====

.Steps

. In the left navigation pane, click *STORAGE* > *Storage VMs*.
. From the *VIEW* menu, select *Health* > *All Storage VMs*.
+
The Health: All Storage VMs is displayed.

. Click *Filter* to view one of the following storage VMs.
[cols="2*",options="header"]
+
|===
| To view| Filter value
a|
*Protected storage VMs*
a|
*Protection Role* is *Protected*
a|
*Unprotected storage VMs*
a|
*Protection Role* is *Unprotected*
|===
+
[NOTE]
====
You cannot view both the protected and unprotected storage VMs at the same time. You will need to clear the existing filter to reapply a new filter option.
====

. Click *Apply Filter*.
+
The Unsaved view displays all the storage VMs that are either protected or unprotected by storage VM disaster recovery based on your filter selections.
