---
permalink: data-protection/task_breaking_a_snapmirror_relationship_from_the_health_volume_details_page.html
sidebar: sidebar
keywords: 
summary: 'You can break a protection relationship from the Volume / Health details page and stop data transfers between a source and destination volume in a SnapMirror relationship. You might break a relationship when you want to migrate data, for disaster recovery, or for application testing. The destination volume is changed to a read-write volume. You cannot break a SnapVault relationship.'
---
= Breaking a SnapMirror relationship from the Volume / Health details page
:icons: font
:imagesdir: ../media/

[.lead]
You can break a protection relationship from the Volume / Health details page and stop data transfers between a source and destination volume in a SnapMirror relationship. You might break a relationship when you want to migrate data, for disaster recovery, or for application testing. The destination volume is changed to a read-write volume. You cannot break a SnapVault relationship.

* You must have the Application Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

. In the Protection tab of the Volume / Health details page, select from the topology the SnapMirror relationship you want to break.
. Right-click the destination and select *Break* from the menu.
+
The Break Relationship dialog box is displayed.

. Click *Continue* to break the relationship.
. In the topology, verify that the relationship is broken.

*Related information*

xref:task_configuring_a_connection_between_workflow_automation_and_unified_manager.adoc[Configuring a connection between Workflow Automation and Unified Manager]
