---
permalink: data-protection/task_break_snapmirror_relationship_from_health_volume_details.html
sidebar: sidebar
keywords: break, snapmirror, relationship, volume, health details
summary: "You can break a protection relationship from the Volume / Health details page and stop data transfers between a source and destination volume in a SnapMirror relationship. You might break a relationship when you want to migrate data, for disaster recovery, or for application testing. The destination volume is changed to a read-write volume. You cannot break a SnapVault relationship."
---
= Breaking a SnapMirror relationship from the Volume / Health details page
:icons: font
:imagesdir: ../media/

[.lead]
You can break a protection relationship from the Volume / Health details page and stop data transfers between a source and destination volume in a SnapMirror relationship. You might break a relationship when you want to migrate data, for disaster recovery, or for application testing. The destination volume is changed to a read-write volume. You cannot break a SnapVault relationship.

*What you'll need*

* You must have the Application Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

.Steps

. In the *Protection* tab of the *Volume / Health* details page, select from the topology the SnapMirror relationship you want to break.
. Right-click the destination and select *Break* from the menu.
+
The Break Relationship dialog box is displayed.

. Click *Continue* to break the relationship.
. In the topology, verify that the relationship is broken.
