---
permalink: data-protection/task_quiescing_a_protection_relationship_from_the_volume_relationships_page.html
sidebar: sidebar
keywords: 
summary: 'From the Volume Relationships page, you can quiesce a protection relationship to temporarily prevent data transfers from occurring. You might quiesce a relationship when you want to create a Snapshot copy of a SnapMirror destination volume that contains a database, and you want to ensure that its contents are stable during the Snapshot copy operation.'
---
= Quiescing a protection relationship from the Volume Relationships page
:icons: font
:imagesdir: ../media/

[.lead]
From the Volume Relationships page, you can quiesce a protection relationship to temporarily prevent data transfers from occurring. You might quiesce a relationship when you want to create a Snapshot copy of a SnapMirror destination volume that contains a database, and you want to ensure that its contents are stable during the Snapshot copy operation.

* You must have the Application Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

The quiesce action does not display in the following instances:

* If RBAC settings do not allow this action; for example, if you have only operator privileges
* When the volume ID is unknown; for example, when you have an intercluster relationship and the destination cluster has not yet been discovered
* When you have not paired Workflow Automation and Unified Manager

. To quiesce transfers for one or more protection relationships, from the Volume Relationships page, select one or more volumes and, on the toolbar, click *Quiesce*.
+
The Quiesce dialog box is displayed.

. Click *Continue*.
+
The status of the quiesce job is displayed at the top of the Volume / Health details page, along with a link to the job details.

. Click the *View details* link to go to the Job details page for additional details and job progress.
. Click the *Back* arrow on your browser to return to the Volume Relationships page.
+
The quiesce job is finished when all job tasks are successfully completed.
