---
permalink: data-protection/task_create_snapmirror_relationship_with_version_flexible_replication.html
sidebar: sidebar
keywords: create, snapmirror, relationship, version-flexible, replication
summary: "You can create a SnapMirror relationship with version-flexible replication. Version-flexible replication enables you to implement SnapMirror protection even if source and destination volumes run under different versions of ONTAP."
---
= Creating a SnapMirror relationship with version-flexible replication
:icons: font
:imagesdir: ../media/

[.lead]
You can create a SnapMirror relationship with version-flexible replication. Version-flexible replication enables you to implement SnapMirror protection even if source and destination volumes run under different versions of ONTAP.

*What you'll need*

* You must have the Application Administrator or Storage Administrator role.
* You must have set up Workflow Automation.
* The source and destination SVMs must each have a SnapMirror license enabled.
* The source and destination SVMs must each run under a version of ONTAP software that supports version-flexible replication.

SnapMirror with version-flexible replication enables you to implement SnapMirror protection even in heterogeneous storage environments in which not all storage is running under one version of ONTAP; however, mirror operations performed under SnapMirror with version-flexible replication do not execute as quickly as they would under traditional block replication SnapMirror.

.Steps

. Display the *Configure Protection* dialog box for the volume that you want to protect.
 ** If you are viewing the Protection tab of the Volume / Health details page, right-click in the topology view that has the name of a volume that you want to protect and select *Protect* > *SnapMirror* from the menu.
 ** If you are viewing the Health: All Volumes view, locate a volume that you want to protect and right-click it; then select *Protect* > *SnapMirror* from the menu.
The Configure Protection dialog box is displayed.
. Click *SnapMirror* to view the *SnapMirror* tab.
. Complete the *Destination Information* area and the *Relationship Settings* area in the *Configure Protection* dialog box.
+
If you specify a destination SVM that runs under an earlier version of ONTAP than the source volume you are protecting, and if that earlier version supports version-flexible replication, this task automatically configures SnapMirror with version-flexible replication.

. If you specify a destination SVM that runs under the same version of ONTAP as that of the source volume, but you still want to configure SnapMirror with version-flexible replication, click *Advanced* to enable version-flexible replication and then click *Apply*.
. Click *Apply*.
+
You are returned to the Volume / Health details page.

. Click the protection configuration job link at the top of the *Volume / Health* details page.
+
The jobs tasks and details are displayed in the Job details page.

. In the *Job* details page, click *Refresh* to update the tasks list and task details associated with the protection configuration job and to determine when the job is complete.
. When the job tasks are complete, click *Back* on your browser to return to the *Volume / Health* details page.
+
The new relationship is displayed in the Volume / Health details page topology view.
