---
permalink: data-protection/task_create_snapmirror_relationships_with_version_flexible_replication.html
sidebar: sidebar
keywords: create, snapmirror, relationships, version-flexible, replication, backup, option
summary: "You can create a SnapMirror relationship with version-flexible replication and backup option capability. Backup option capability enables you to implement SnapMirror protection and also retain multiple versions of backup copies at the destination location."
---
= Creating SnapMirror relationships with version-flexible replication with backup option
:icons: font
:imagesdir: ../media/

[.lead]
You can create a SnapMirror relationship with version-flexible replication and backup option capability. Backup option capability enables you to implement SnapMirror protection and also retain multiple versions of backup copies at the destination location.

*What you'll need*

* You must have the Application Administrator or Storage Administrator role.
* You must have set up Workflow Automation.
* The source and destination SVMs must each have a SnapMirror license enabled.
* The source and destination SVMs must each have a SnapVault license enabled.
* The source and destination SVMs must each run under a version of ONTAP software that supports version-flexible replication.

Configuring SnapMirror with backup option capability enables you to protect your data with SnapMirror disaster recovery capabilities, such as volume failover ability, and at the same time provide SnapVault capabilities, such as multiple backup copy protection.

.Steps

. Display the *Configure Protection* dialog box for the volume that you want to protect.
 ** If you are viewing the Protection tab of the Volume / Health details page, right-click in the topology view the name of a volume that you want to protect and select *Protect* > *SnapMirror* from the menu.
 ** If you are viewing the Health: All Volumes view, locate a volume you want to protect and right-click it; then select *Protect* > *SnapMirror* from the menu.
The Configure Protection dialog box is displayed.
. Click *SnapMirror* to view the *SnapMirror* tab.
. Complete the *Destination Information* area and the *Relationship Settings* area in the *Configure Protection* dialog box.
. Click *Advanced* to display the *Advanced Destination Settings* dialog box.
. If the *Version-Flexible Replication* check box is not already selected, select it now.
. Select the *With backup option* check box to enable backup option capability; then click *Apply*.
. Click *Apply*.
+
You are returned to the Volume / Health details page.

. Click the protection configuration job link at the top of the *Volume / Health* details page.
+
The jobs tasks and details are displayed in the Job details page.

. In the *Job* details page, click *Refresh* to update the task list and task details associated with the protection configuration job and to determine when the job is complete.
. When the job tasks are complete, click *Back* on your browser to return to the *Volume / Health* details page.
+
The new relationship is displayed in the Volume / Health details page topology view.
