---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html
sidebar: sidebar
keywords: create, snapmirror, protection, relationship,  volume, health details page
summary: "You can use the Volume / Health details page to create a SnapMirror relationship so that data replication is enabled for protection purposes. SnapMirror replication enables you to restore data from the destination volume in the event of data loss on the source."
---
= Creating a SnapMirror protection relationship from the Volume / Health details page
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Volume / Health details page to create a SnapMirror relationship so that data replication is enabled for protection purposes. SnapMirror replication enables you to restore data from the destination volume in the event of data loss on the source.

*What you'll need*

* You must have the Application Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

The *Protect* menu does not display in the following instances:

* If RBAC settings do not allow this action: for example, if you have only operator privileges
* When the volume ID is unknown: for example, when you have an intercluster relationship and the destination cluster has not yet been discovered

You can perform up to 10 protection jobs simultaneously with no performance impact. You might experience some performance impact when you run between 11 and 30 jobs simultaneously. Running more than 30 jobs simultaneously is not recommended.

.Steps

. In the *Protection tab* of the *Volume / Health* details page, right-click in the topology view the name of a volume that you want to protect.
. Select *Protect* > *SnapMirror* from the menu.
+
The Configure Protection dialog box is displayed.

. Click *SnapMirror* to view the *SnapMirror* tab and to configure the destination information.
. Click *Advanced* to set the space guarantee, as needed, and then click *Apply*.
. Complete the *Destination Information* area and the *Relationship Settings* area in the *Configure Protection* dialog box.
. Click *Apply*.
+
You are returned to the Volume / Health details page.

. Click the protection configuration job link at the top of the *Volume / Health* details page.
+
The job's tasks and details are displayed in the Job details page.

. In the *Job* details page, click *Refresh* to update the tasks list and task details associated with the protection configuration job and to determine when the job is complete.
. When the job tasks are complete, click *Back* on your browser to return to the *Volume / Health* details page.
+
The new relationship is displayed in the Volume / Health details page topology view.

Depending on the destination SVM you specified during configuration or on the options you enabled in your Advanced settings, the resulting SnapMirror relationship might be one of several possible variations:

* If you specified a destination SVM that runs under the same or a newer version of ONTAP compared to that of the source volume, a block-replication-based SnapMirror relationship is the default result.
* If you specified a destination SVM that runs under the same or a newer version of ONTAP compared to that of the source volume, but you enabled version-flexible replication in the Advanced settings, a SnapMirror relationship with version-flexible replication is the result.
* If you specified a destination SVM that runs under an earlier version of ONTAP, or a version that is higher than that of the source volume and the earlier version supports version-flexible replication, a SnapMirror relationship with version-flexible replication is the automatic result.
